[Economy]
    EconomyModule = DTLNSLMoneyModule
    HGAvatarAs     = "LocalAvatar"
    SendAlert      = false
    ; EconomyHelper = https://the.currency.machine.fdqn:port/folder/folder...
    SellEnabled    = true
    PriceUpload = 0
    PriceGroupCreate = 0
    currency = "Dorito"
    CurrencyServer = "${Const|BaseURL}:1026/"
    UserServer     = "${Const|BaseURL}:${Const|PublicPort}"
    ; CheckServerCert = false
    ; CACertFilename  = ""
    ; CACertPassword  = ""
    ; CheckClientCert    = false
    ; ClientCertFilename = "client_cert.p12"
    ; ClientCertPassword = "" 
