[Map]
    GenerateMaptiles = true
    MapImageModule = "MapImageModule"
    ; MaptileRefresh = 0
    ; MaptileStaticUUID = "00000000-0000-0000-0000-000000000000"
    ; TextureOnMapTile = true
    ; DrawPrimOnMapTile = true
    ; TexturePrims = true
    ; TexturePrimSize = 48
    ; RenderMeshes = false
    ; MapColorWater = "#3399FF"
    ; MapColor1 = "#A58976"
    ; MapColor2 = "#455931"
    ; MapColor3 = "#A29A8D"
    ; MapColor4 = "#C8C8C8"