[Messaging]
    ; OfflineMessageModule = OfflineMessageModule
    OfflineMessageModule = "Offline Message Module V2"
    OfflineMessageURL = http://not.let-us.cyou:8003
	; OfflineMessageURL = https://not.let-us.cyou/ostools/offline.php
    ; StorageProvider = OpenSim.Data.MySQL.dll
    MuteListModule = MuteListModule
    ; ForwardOfflineGroupMessages = true
