[RemoteAdmin]
    enabled = false
    port = ${Const|PrivURL}
    access_password = "CHANGE_ME_CONSOLE_PASS"
    access_ip_addresses = 0.0.0.0
    create_region_enable_voice = false
    create_region_public = false
    ;; enabled_methods = admin_broadcast|admin_save_oar|admin_save_xml
    enabled_methods = all
    default_male = Default Male
    default_female = Default Female
    ; copy_folders = false
    ; default_appearance = default_appearance.xml
