[Search]
SearchURL = 
"http://not.let-us.cyou/api4opensim/query.php?gk=http://not.let-us.cyou:8002"

[SimulatorFeatures]
    ;SearchServerURI = "http://127.0.0.1:9000/
    DestinationGuideURI = "https://not.let-us.cyou/api4opensim/guide"