;; I-Grid region file - {{NAME}}
;; Generated by generate_configs.py. Do not edit by hand.

[{{NAME}}]
    RegionUUID = {{REGION_UUID}}
    Location = {{X}},{{Y}}
    SizeX = {{SIZE_X}}
    SizeY = {{SIZE_Y}}
    InternalPort = {{PORT}}
    InternalAddress = 0.0.0.0
    ExternalHostName = "{{REGION_HOST}}"

    ;; Strict inventory / content flow (no mesh prim clamp)
    ClampPrimSize = false
    NonPhysicalPrimMax = 0
    PhysicalPrimMax = 0

    ;; Unlimited prims — advertised as 999555333 (viewer shows max, var regions scale)
    MaxPrims = 999555333

    ;; From this simulator the region "arrives" at the grid already authorized.
    ; (the manager registers regions automatically once the sim connects)
