;; I-Grid  Fresh Metaverse  -  Robust grid server (port {{ROBUST_PORT}})
;; Generated by generate_configs.py. Do not edit - regenerate instead.

[Const]
    BaseHostname = "{{HOST}}"
    BaseURL = "http://${Const|BaseHostname}"
    PublicPort = "{{ROBUST_PORT}}"
    PrivatePort = "{{PRIVATE_PORT}}"

[Startup]
    console = basic
    ;; Memory limiter disabled 2026-09-14: the 2GB cap (in-process watchdog
    ;; + OS Job Object) killed/restricted Robust under real grid load.
    ;; Same policy as region sims (MemoryLimit = 0).
    MemoryLimit = 0

    RegistryLocation = "."
    ConfigDirectory = "robust-include"
    PIDFile = "./data/robust.pid"

    ConsoleHistoryFileEnabled = true
    ConsoleHistoryFile = "./data/RobustConsoleHistory.txt"
    ConsoleHistoryFileLines = 100

    NoVerifyCertChain = true
    NoVerifyCertHostname = true

[ServiceList]
    ;; --- core grid services ---
    AssetServiceConnector = "${Const|PrivatePort}/OpenSim.Server.Handlers.dll:AssetServiceConnector"
    InventoryInConnector = "${Const|PrivatePort}/OpenSim.Server.Handlers.dll:XInventoryInConnector"
    GridServiceConnector = "${Const|PrivatePort}/OpenSim.Server.Handlers.dll:GridServiceConnector"
    GridInfoServerInConnector = "${Const|PublicPort}/OpenSim.Server.Handlers.dll:GridInfoServerInConnector"
     AuthenticationServiceConnector = "${Const|PrivatePort}/OpenSim.Server.Handlers.dll:AuthenticationServiceConnector"
     ;; OpenID is disabled by default. Enable it only when the endpoint is protected and intentionally deployed.
     ; OpenIdServerConnector = "${Const|PublicPort}/OpenSim.Server.Handlers.dll:OpenIdServerConnector"
    AvatarServiceConnector = "${Const|PrivatePort}/OpenSim.Server.Handlers.dll:AvatarServiceConnector"
    LLLoginServiceInConnector = "${Const|PublicPort}/OpenSim.Server.Handlers.dll:LLLoginServiceInConnector"
    PresenceServiceConnector = "${Const|PrivatePort}/OpenSim.Server.Handlers.dll:PresenceServiceConnector"
    UserAccountServiceConnector = "${Const|PrivatePort}/OpenSim.Server.Handlers.dll:UserAccountServiceConnector"
    GridUserServiceConnector = "${Const|PrivatePort}/OpenSim.Server.Handlers.dll:GridUserServiceConnector"
    AgentPreferencesServiceConnector = "${Const|PrivatePort}/OpenSim.Server.Handlers.dll:AgentPreferencesServiceConnector"
    FriendsServiceConnector = "${Const|PrivatePort}/OpenSim.Server.Handlers.dll:FriendsServiceConnector"
    GroupsServiceConnector = "${Const|PrivatePort}/OpenSim.Addons.Groups.dll:GroupsServiceRobustConnector"
    MapAddServiceConnector = "${Const|PrivatePort}/OpenSim.Server.Handlers.dll:MapAddServiceConnector"
    MapGetServiceConnector = "${Const|PublicPort}/OpenSim.Server.Handlers.dll:MapGetServiceConnector"
    UserProfilesServiceConnector = "${Const|PublicPort}/OpenSim.Server.Handlers.dll:UserProfilesConnector"
    MuteListConnector = "${Const|PrivatePort}/OpenSim.Server.Handlers.dll:MuteListServiceConnector"
    EstateDataService = "${Const|PrivatePort}/OpenSim.Server.Handlers.dll:EstateDataRobustConnector"
    ;; --- hypergrid services ---
    GatekeeperServiceInConnector = "${Const|PublicPort}/OpenSim.Server.Handlers.dll:GatekeeperServiceInConnector"
    UserAgentServerConnector = "${Const|PublicPort}/OpenSim.Server.Handlers.dll:UserAgentServerConnector"
    HeloServiceInConnector = "${Const|PublicPort}/OpenSim.Server.Handlers.dll:HeloServiceInConnector"
    HGFriendsServerConnector = "${Const|PublicPort}/OpenSim.Server.Handlers.dll:HGFriendsServerConnector"
    HGGroupsServiceConnector = "${Const|PublicPort}/OpenSim.Addons.Groups.dll:HGGroupsServiceRobustConnector"
    InstantMessageServerConnector = "${Const|PublicPort}/OpenSim.Server.Handlers.dll:InstantMessageServerConnector"
    HGInventoryServiceConnector = "HGInventoryService@${Const|PublicPort}/OpenSim.Server.Handlers.dll:XInventoryInConnector"
    HGAssetServiceConnector = "HGAssetService@${Const|PublicPort}/OpenSim.Server.Handlers.dll:AssetServiceConnector"
    QuicProxyConnector = "${Const|PrivatePort}/OpenSim.Server.Handlers.dll:QuicProxyConnector"
    OfflineIMConnector = "${Const|PrivatePort}/OpenSim.Addons.OfflineIM.dll:OfflineIMServiceRobustConnector"

[Network]
    port = ${Const|PrivatePort}
    ExternalHostName = "${Const|BaseHostname}"
    ;; Per-process cute 404 page — file at 404/robust.html relative to Robust CWD
     http_404 = "404/robust.html"
     HttpBodyMaxLenMAX = 5242880
     AllowllHTTPRequestIn = false

     ;; Explicit source addresses allowed to call internal control-plane endpoints.
     ;; Keep this list narrow; loopback is always trusted. Do not add public clients or arbitrary grids.
     ControlPlaneTrustedHosts = 127.0.0.1

[AccessControl]
    AllowedClients = ""

[DatabaseService]
    StorageProvider = "OpenSim.Data.{{DB_PROVIDER}}.dll"
    ConnectionString = "{{DB_CONN}}"

[AssetService]
    LocalServiceModule = "OpenSim.Services.AssetService.dll:AssetService"
    ;; Assets live in their own database (see ASSET_DB_CONN, separate from
    ;; the grid database). No filesystem/FSAssets.
    StorageProvider = "OpenSim.Data.{{DB_PROVIDER}}.dll"
    ConnectionString = "{{ASSET_DB_CONN}}"
    ;; Accept remote asset requests from any host (backwards compat; links too)
    WhitelistedSenders = "*.{{HOST}};*"
    ;; Base files for the world map (very small, safe with SQLite)
    UseGridFileWatching = True

[InventoryService]
    LocalServiceModule = "OpenSim.Services.InventoryService.dll:XInventoryService"

[GridService]
    LocalServiceModule = "OpenSim.Services.GridService.dll:GridService"
    StorageProvider = "{{GRID_STORAGE_PROVIDER}}"
    HypergridLinker = true
    GatekeeperURI = "${Const|BaseURL}:${Const|PublicPort}"
    ExportSupported = true

[AuthenticationService]
    LocalServiceModule = "OpenSim.Services.AuthenticationService.dll:PasswordAuthenticationService"

[OpenIdService]
    AuthenticationServiceModule = "OpenSim.Services.AuthenticationService.dll:PasswordAuthenticationService"
    UserAccountServiceModule = "OpenSim.Services.UserAccountService.dll:UserAccountService"

[UserAccountService]
    StorageProvider = "{{ACCOUNT_STORAGE_PROVIDER}}"
    LocalServiceModule = "OpenSim.Services.UserAccountService.dll:UserAccountService"
    AuthenticationService = "OpenSim.Services.AuthenticationService.dll:PasswordAuthenticationService"
    PresenceService = "OpenSim.Services.PresenceService.dll:PresenceService"
    GridService = "OpenSim.Services.GridService.dll:GridService"
    InventoryService = "OpenSim.Services.InventoryService.dll:XInventoryService"
    AvatarService = "OpenSim.Services.AvatarService.dll:AvatarService"
    GridUserService = "OpenSim.Services.UserAccountService.dll:GridUserService"
    CreateDefaultAvatarEntries = true

[GridUserService]
    LocalServiceModule = "OpenSim.Services.UserAccountService.dll:GridUserService"

[AgentPreferencesService]
    LocalServiceModule = "OpenSim.Services.UserAccountService.dll:AgentPreferencesService"

[PresenceService]
    StorageProvider = "{{PRESENCE_STORAGE_PROVIDER}}"
    LocalServiceModule = "OpenSim.Services.PresenceService.dll:PresenceService"

[AvatarService]
    LocalServiceModule = "OpenSim.Services.AvatarService.dll:AvatarService"

[FriendsService]
    LocalServiceModule = "OpenSim.Services.FriendsService.dll:FriendsService"

[EstateService]
    LocalServiceModule = "OpenSim.Services.EstateService.dll:EstateDataService"

[UserProfilesService]
    LocalServiceModule = "OpenSim.Services.UserProfilesService.dll:UserProfilesService"
    Enabled = true
    UserAccountService = "OpenSim.Services.UserAccountService.dll:UserAccountService"
    AuthenticationServiceModule = "OpenSim.Services.AuthenticationService.dll:PasswordAuthenticationService"

[LibraryService]
    LibraryName = "Fresh Metaverse Library"
    DefaultLibrary = "./inventory/Libraries.xml"

[MuteListService]
    LocalServiceModule = "OpenSim.Services.MuteListService.dll:MuteListService"

[LoginService]
    UserAgentService = "OpenSim.Services.HypergridService.dll:UserAgentService"
    HGInventoryServicePlugin = "HGInventoryService@OpenSim.Services.HypergridService.dll:HGSuitcaseInventoryService"
    LocalServiceModule = "OpenSim.Services.LLLoginService.dll:LLLoginService"
    UserAccountService = "OpenSim.Services.UserAccountService.dll:UserAccountService"
    GridUserService = "OpenSim.Services.UserAccountService.dll:GridUserService"
    AuthenticationService = "OpenSim.Services.AuthenticationService.dll:PasswordAuthenticationService"
    InventoryService = "OpenSim.Services.InventoryService.dll:XInventoryService"
    AvatarService = "OpenSim.Services.AvatarService.dll:AvatarService"
    PresenceService = "OpenSim.Services.PresenceService.dll:PresenceService"
    GridService = "OpenSim.Services.GridService.dll:GridService"
    SimulationService = "OpenSim.Services.Connectors.dll:SimulationServiceConnector"
    LibraryService = "OpenSim.Services.InventoryService.dll:LibraryService"
    FriendsService = "OpenSim.Services.FriendsService.dll:FriendsService"

    WelcomeMessage = "Welcome to Fresh Metaverse!"
    AllowRemoteSetLoginLevel = "false"
    Region_MainLand01_X2000Y2000 = "DefaultRegion, DefaultHGRegion, FallbackRegion"
    MapTileURL = "${Const|BaseURL}:${Const|PublicPort}/"
    SRV_HomeURI = "${Const|BaseURL}:${Const|PublicPort}"
    SRV_InventoryServerURI = "${Const|BaseURL}:${Const|PublicPort}"
    SRV_AssetServerURI = "${Const|BaseURL}:${Const|PublicPort}"
    SRV_ProfileServerURI = "${Const|BaseURL}:${Const|PublicPort}"
    SRV_FriendsServerURI = "${Const|BaseURL}:${Const|PublicPort}"
    SRV_IMServerURI = "${Const|BaseURL}:${Const|PublicPort}"
    SRV_GroupsServerURI = "${Const|BaseURL}:${Const|PublicPort}"
    DSTZone = "America/Los_Angeles;Pacific Standard Time"
    AllowLoginFallbackToAnyRegion = false

[MapImageService]
    LocalServiceModule = "OpenSim.Services.MapImageService.dll:MapImageService"

[GridInfoService]
    login = ${Const|BaseURL}:${Const|PublicPort}/
    gridname = "Fresh Metaverse"
    gridnick = "FreshMetaverse"
	welcome = https://os.tasia.work.gd/web/
    economy = https://os.tasia.work.gd/ostools/
    about= https://os.tasia.work.gd/
    register = https://os.tasia.work.gd/amber/register.php
    help = https://os.tasia.work.gd/
    password = https://os.tasia.work.gd/amber/register.php
    gatekeeper = ${Const|BaseURL}:${Const|PublicPort}/
    ;GridStatus = ${Const|BaseURL}:${Const|PublicPort}/GridStatus
    GridStatusRSS = ${Const|BaseURL}:${Const|PublicPort}/GridStatusRSS
    web_profile_url = os.tasia.work.gd/ostools/profile/[AGENT_NAME]
    search = https://os.tasia.work.gd/search

[Messaging]
    OfflineIMService = "OpenSim.Addons.OfflineIM.dll:OfflineIMService"
    StorageProvider = "{{OFFLINE_STORAGE_PROVIDER}}"
    ;; Offline group IMs must be forwarded even when members are offline
    ForwardOfflineGroupMessages = true

[Groups]
    OfflineIMService = "OpenSim.Addons.OfflineIM.dll:OfflineIMService"
    UserAccountService = "OpenSim.Services.UserAccountService.dll:UserAccountService"
    HomeURI = "${Const|BaseURL}:${Const|PublicPort}"
    MaxAgentGroups = 500

;; ---------------------------------------------------------------------------
;;  Hypergrid
;; ---------------------------------------------------------------------------

[Hypergrid]
    HomeURI = "${Const|BaseURL}:${Const|PublicPort}"
    GatekeeperURI = "${Const|BaseURL}:${Const|PublicPort}"

[GatekeeperService]
    LocalServiceModule = "OpenSim.Services.HypergridService.dll:GatekeeperService"
    UserAccountService = "OpenSim.Services.UserAccountService.dll:UserAccountService"
    UserAgentService = "OpenSim.Services.HypergridService.dll:UserAgentService"
    PresenceService = "OpenSim.Services.PresenceService.dll:PresenceService"
    GridUserService = "OpenSim.Services.UserAccountService.dll:GridUserService"
    GridService = "OpenSim.Services.GridService.dll:GridService"
    AuthenticationService = "OpenSim.Services.Connectors.dll:AuthenticationServicesConnector"
    SimulationService = "OpenSim.Services.Connectors.dll:SimulationServiceConnector"
    ExternalName = "${Const|BaseURL}:${Const|PublicPort}"
    AllowTeleportsToAnyRegion = true
    ForeignAgentsAllowed = true

[UserAgentService]
    ; Behind the Pangolin tunnel every viewer arrives as 127.0.0.1, so the
    ; IP-match check in VerifyClient can never pass for direct-connecting
    ; foreign grids (they see the real client IP) and kills all outgoing HG
    ; teleports. Bypass it: agent-token auth (VerifyAgent) still applies.
    BypassClientVerification = true
    LocalServiceModule = "OpenSim.Services.HypergridService.dll:UserAgentService"
    GridUserService = "OpenSim.Services.UserAccountService.dll:GridUserService"
    GridService = "OpenSim.Services.GridService.dll:GridService"
    GatekeeperService = "OpenSim.Services.HypergridService.dll:GatekeeperService"
    PresenceService = "OpenSim.Services.PresenceService.dll:PresenceService"
    FriendsService = "OpenSim.Services.FriendsService.dll:FriendsService"
    UserAccountService = "OpenSim.Services.UserAccountService.dll:UserAccountService"
    ;; Allow normal residents (level 0) to HG-teleport out; higher levels are staff
    ForeignTripsAllowed_Level_0 = true
    ForeignTripsAllowed_Level_50 = true
    ForeignTripsAllowed_Level_100 = true
    ForeignTripsAllowed_Level_150 = true
    ForeignTripsAllowed_Level_200 = true
    ForeignTripsAllowed_Level_250 = true

[HGInventoryService]
    LocalServiceModule = "OpenSim.Services.HypergridService.dll:HGSuitcaseInventoryService"
    UserAccountsService = "OpenSim.Services.UserAccountService.dll:UserAccountService"
    AvatarService = "OpenSim.Services.AvatarService.dll:AvatarService"
    AuthType = None
    HomeURI = "${Const|BaseURL}:${Const|PublicPort}"

[HGAssetService]
    LocalServiceModule = "OpenSim.Services.HypergridService.dll:HGAssetService"
    UserAccountsService = "OpenSim.Services.UserAccountService.dll:UserAccountService"
    HomeURI = "${Const|BaseURL}:${Const|PublicPort}"
    BackingService = "OpenSim.Services.AssetService.dll:AssetService"

[HGFriendsService]
    LocalServiceModule = "OpenSim.Services.HypergridService.dll:HGFriendsService"
    UserAgentService = "OpenSim.Services.HypergridService.dll:UserAgentService"
    FriendsService = "OpenSim.Services.FriendsService.dll:FriendsService"
    UserAccountService = "OpenSim.Services.UserAccountService.dll:UserAccountService"
    GridService = "OpenSim.Services.GridService.dll:GridService"
    PresenceService = "OpenSim.Services.PresenceService.dll:PresenceService"

[HGInstantMessageService]
    LocalServiceModule = "OpenSim.Services.HypergridService.dll:HGInstantMessageService"
    GridService = "OpenSim.Services.GridService.dll:GridService"
    PresenceService = "OpenSim.Services.PresenceService.dll:PresenceService"
    UserAgentService = "OpenSim.Services.HypergridService.dll:UserAgentService"
    InGatekeeper = True
[ExperienceService]
    LocalServiceModule = "OpenSim.Services.ExperienceService.dll:ExperienceService"
    UserAccountService = "OpenSim.Services.UserAccountService.dll:UserAccountService"
;; ---------------------------------------------------------------------------
;;  QUIC transport (public viewer port {{QUIC_PORT}})
;; ---------------------------------------------------------------------------

[ClientStack.Quic]
    Enabled = true
    AdvertiseInLoginResponse = true
    AdvertiseHost = "{{REGION_HOST}}"
    AdvertisePort = {{QUIC_PORT}}
    Port = {{QUIC_PORT}}
    CertificatePath = "{{CENTRAL_QUIC_P12}}"
    CertificatePassword = "{{QUIC_CERT_PASS}}"

[QuicProxy]
    Enabled = true
    Port = {{QUIC_PORT}}
    ALPN = opensim-ll/1
    CertificatePath = {{CENTRAL_QUIC_PEM}}
    PrivateKeyPath = {{CENTRAL_QUIC_KEY}}
    ; Password for PKCS#12 files (same cert as [ClientStack.Quic]).
    ; Needed so the native QUIC listener can load exportable keys for
    ; OpenSSL-based MsQuic on Windows 10.
    CertificatePassword = "{{QUIC_CERT_PASS}}"
    ; Valid simulator QUIC port pool (Quick-G brain allocation range).
    ; quicPort values outside this pool are treated as stale and ignored,
    ; keeping the LLUDP route so teleports keep working.
    QuicPoolStart = {{REGION_QUIC_POOL_START}}
    QuicPoolEnd = {{REGION_QUIC_POOL_END}}

[QuickG]
    ; auto = start automatically only on Windows 10
    ; true = force start
    ; false = disable
    ; 2026-09-14: disabled — native QUIC listeners (OpenSSL MsQuic) replace
    ; the Quick-G bridge. Robust binds 22002 natively; sims listen on fixed
    ; per-region native ports (region_quic_start+i). Keep binary for rollback.
    Enabled = false
    Executable = Quick-G.exe

    ; Public viewer-facing QUIC port
    Port = {{QUIC_PORT}}

    ; Private Quick-G health/control port. NEVER expose this publicly.
    ControlPort = {{QUICKG_CONTROL_PORT}}

    ; Quick-G region brain
    BrainBind = {{QUICKG_BRAIN_BIND}}
    BrainPort = {{QUICKG_BRAIN_PORT}}
    BrainLeaseSeconds = {{QUICKG_BRAIN_LEASE_SECONDS}}

    ; Automatic region QUIC port allocation
    RegionPortStart = {{REGION_QUIC_POOL_START}}
    RegionPortEnd = {{REGION_QUIC_POOL_END}}
    RegionPortExclude = {{REGION_QUIC_POOL_EXCLUDE}}

    ; Quick-G is mandatory. If it fails, Robust QUIC startup pauses.
    AllowNativeQuicFallback = false

    CertificatePath = {{CENTRAL_QUIC_PEM}}
    PrivateKeyPath = {{CENTRAL_QUIC_KEY}}
    ALPN = opensim-ll/1
