;; I-Grid  Fresh Metaverse  -  Per-region simulator configuration (grid mode)
;; One process per region. Generated by generate_configs.py.

[Startup]
    console = basic
    WorldMapModule = "HGWorldMap"
    ;; Soft watchdog: forces GC + warns near limit, never kills.
    ;; Hard 2GB cap enforced by the manager at OS level.
    MemoryLimit = 0
    
    PIDFile = "{{DATA_DIR}}/sim.pid"
    EstimatedRegionCount = 1

    ConsoleHistoryFileEnabled = true
    ConsoleHistoryFile = "{{DATA_DIR}}/OpenSimConsoleHistory.txt"

    physics = {{PHYSICS_ENGINE}}
    meshing = {{MESHING}}
    {{CLAMP_LINE}}

    ;; Load region definitions from the generated per-sim regions directory.
    regionload_regionsdir = "{{REGIONS_DIR}}"
    allow_regionless = false
    region_modules = "TasiaAddons.RemoteSound.dll,TasiaAddons.LoginSecurity.dll,TasiaAddons.MACAudit.dll,TasiaAddons.ChatAudit.dll,TasiaAddons.RestartModule.dll,TasiaAddons.DisplayNameCaps.dll"
[Const]
    RobustHGAES = "unknown"
    ;; Grid identity is ALWAYS os.tasia.work.gd (Robust). ok.tasia.work.gd is
    ;; ONLY for region endpoints ([Network] ExternalHostName, QUIC AdvertiseHost,
    ;; per-sim CAPS/LLUDP listeners). Mixing them breaks HG identity checks.
    BaseHostname = "{{HOST}}"
    BaseURL = "http://${Const|BaseHostname}"
    PublicPort = "{{ROBUST_PORT}}"
    PrivatePort = "{{PRIVATE_PORT}}"

;; ---------------------------------------------------------------------------
;;  Estate
;;  In grid mode the owner account must already exist at the grid (Robust).
;;  The manager creates it on first run (see regions.yaml → estate.owner).
;; ---------------------------------------------------------------------------

[Estates]
    DefaultEstateName = {{ESTATE_NAME}}
    DefaultEstateOwnerName = "{{ESTATE_OWNER}}"

[Network]
    InternalPort = {{PORT}}
    http_listener_port = {{SIM_HTTP_PORT}}
    ExternalHostName = "{{REGION_HOST}}"
    ;; Cute per-region 404 page — file is at 404/{{NAME}}.html relative to sim CWD
     http_404 = "404/{{NAME}}.html"
     MaxAgentConnections = 100

     ;; Explicit source addresses allowed to call internal control-plane endpoints.
     ;; Keep this list narrow; loopback is always trusted. Do not add public clients or arbitrary grids.
     ControlPlaneTrustedHosts = 127.0.0.1, 51.89.54.203, 51.68.184.194, 116.202.127.9, 194.140.198.33, 167.17.76.141

[ClientStack.LindenUDP]
    ; DisableFacelights = "false"

[ClientStack.LindenCaps]
    ; Event queue
    Cap_EventQueueGet = "localhost"
    ; Viewer stats
    Cap_ViewerStats = "localhost"
    ; Assets
    Cap_GetTexture = "localhost"
    Cap_GetMesh = "localhost"
    Cap_GetMesh2 = "localhost"

    ; Inventory
    Cap_FetchInventoryDescendents2 = "localhost"
    Cap_FetchInventory2 = "localhost"
    Cap_CopyInventoryFromNotecard = "localhost"

    ; Uploads / editing
    Cap_NewFileAgentInventory = "localhost"
    Cap_NewFileAgentInventoryVariablePrice = "localhost"
    Cap_UploadBakedTexture = "localhost"
    Cap_UploadObjectAsset = "localhost"
    Cap_UpdateNotecardAgentInventory = "localhost"
    Cap_UpdateNotecardTaskInventory = "localhost"
    Cap_UpdateScriptAgent = "localhost"
    Cap_UpdateScriptTask = "localhost"

    ; Region / map
    Cap_MapLayer = "localhost"
    Cap_MapLayerGod = "localhost"
    Cap_HomeLocation = "localhost"
    Cap_RemoteParcelRequest = "localhost"
    Cap_ParcelPropertiesUpdate = "localhost"

    ; Media / environment
    Cap_EnvironmentSettings = "localhost"
    Cap_ObjectMedia = "localhost"
    Cap_ObjectMediaNavigate = "localhost"

    ; People / groups
    Cap_AvatarPickerSearch = "localhost"
    Cap_GetDisplayNames = "localhost"
    Cap_GroupMemberData = "localhost"

    ; Custom Tasia module
    Cap_SetDisplayName = "localhost"
    DisplayNameManagerChatEnabled = true
    DisplayNameManagerChatChannel = 77
	
[SimulatorFeatures]
    DestinationGuideURI = "https://os.tasia.work.gd/ostools/guide.php"
;; ---------------------------------------------------------------------------
;;  Modules (HG-aware)
;; ---------------------------------------------------------------------------

[Modules]
    ;; Grid services — remote Robust
    GridServices            = RegionGridServicesConnector
    AvatarServices          = RemoteAvatarServicesConnector
    SimulationServices      = RemoteSimulationConnectorModule
    NeighbourServices       = NeighbourServicesOutConnector
    LandServices            = RemoteLandServicesConnector
    UserAccountServices     = RemoteUserAccountServicesConnector
    PresenceServices        = RemotePresenceServicesConnector
    GridUserServices        = RemoteGridUserServicesConnector
    AgentPreferencesServices= RemoteAgentPreferencesServicesConnector
    AuthenticationServices  = "RemoteAuthenticationServicesConnector"
    UserAliasServices       = RemoteUserAliasServicesConnector
    MuteListService         = RemoteMuteListServicesConnector
    ExperienceServices      = RemoteExperienceServicesConnector

    ;; HG modules
    EntityTransferModule    = HGEntityTransferModule
    InventoryServices       = HGInventoryBroker
    InventoryAccessModule   = HGInventoryAccessModule
    AssetServices           = RegionAssetConnector
    FriendsModule           = HGFriendsModule
    UserManagementModule    = HGUserManagementModule
    MapImageService         = MapImageServiceModule
    SearchModule            = BasicSearchModule
    AuthorizationServices   = RemoteAuthorizationServicesConnector
    Setup_FriendConference = TasiaAddons.FriendConference.FriendConferenceModule
    ;; Local features
    LibraryModule           = true
    LandServiceInConnector  = true
    NeighbourServiceInConnector = true
    SimulationServiceInConnector = true

    ;; Asset caching
    AssetCaching = FlotsamAssetCache

    ;; Plugins
    Setup_RestartModule = TasiaAddons.RestartModule.RestartModule

[RestartModule]
    ApiEnabled = true
    ApiToken = "{{CONSOLE_PASS}}"
    ApiPathPrefix = "/tasia-ngc/restart"
    DefaultDelaySeconds = 60

;; ---------------------------------------------------------------------------
;;  Grid service endpoints (private services on {{PRIVATE_PORT}}, public HG on {{ROBUST_PORT}})
;; ---------------------------------------------------------------------------

[GridService]
    GridServerURI = "http://127.0.0.1:{{PRIVATE_PORT}}"
    HypergridLinker = true
    AllowHypergridMapSearch = true
    Gatekeeper = "${Const|BaseURL}:${Const|PublicPort}"
    NetworkConnector = "OpenSim.Services.Connectors.dll:GridServicesConnector"
    LocalServiceModule = "OpenSim.Services.GridService.dll:GridService"
    AssetService = "OpenSim.Services.Connectors.dll:AssetServicesConnector"

[SimulationService]
    SimulationServerURI = "http://127.0.0.1:{{PRIVATE_PORT}}"

[AssetService]
    AssetServerURI = "http://127.0.0.1:{{PRIVATE_PORT}}"
    LocalGridAssetService = "OpenSim.Services.Connectors.dll:AssetServicesConnector"
    HypergridAssetService = "OpenSim.Services.Connectors.dll:HGAssetServiceConnector"

[InventoryService]
    InventoryServerURI = "http://127.0.0.1:{{PRIVATE_PORT}}"
    LocalGridInventoryService = "OpenSim.Region.CoreModules.dll:RemoteXInventoryServicesConnector"

[UserAccountService]
    UserAccountServerURI = "http://127.0.0.1:{{PRIVATE_PORT}}"

[AuthenticationService]
    AuthenticationServerURI = "http://127.0.0.1:{{PRIVATE_PORT}}"

[PresenceService]
    PresenceServerURI = "http://127.0.0.1:{{PRIVATE_PORT}}"

[UserAgentService]
    ;; UserAgentServerConnector listens on the PUBLIC port (22000), not private.
    UserAgentServerURI = "http://127.0.0.1:{{ROBUST_PORT}}"

[MuteListService]
    MuteListServerURI = "http://127.0.0.1:{{PRIVATE_PORT}}"

[EstateService]
    EstateServerURI = "http://127.0.0.1:{{PRIVATE_PORT}}"

[AvatarService]
    AvatarServerURI = "http://127.0.0.1:{{PRIVATE_PORT}}"

[FriendsService]
    FriendsServerURI = "http://127.0.0.1:{{PRIVATE_PORT}}"
    Connector = "OpenSim.Services.Connectors.dll:FriendsServicesConnector"

[AgentPreferencesService]
    AgentPreferencesServerURI = "http://127.0.0.1:{{PRIVATE_PORT}}"

[Friends]
    Connector = "OpenSim.Services.Connectors.dll:FriendsServicesConnector"

[ExperienceService]
    ExperienceServerURI = "http://127.0.0.1:{{PRIVATE_PORT}}"
    LocalServiceModule = "OpenSim.Services.Connectors.dll:RemoteExperienceServicesConnector"

[GridUserService]
    GridUserServerURI = "http://127.0.0.1:{{PRIVATE_PORT}}"
    LocalServiceModule = "OpenSim.Services.Connectors.dll:GridUserServicesConnector"

[UserAliasService]
    UserAliasServerURI = "http://127.0.0.1:{{PRIVATE_PORT}}"

[MapService]
    MapTileURL = "${Const|BaseURL}:${Const|PublicPort}/"

[MapImageService]
    MapImageServerURI = "http://127.0.0.1:{{PRIVATE_PORT}}"
    LocalServiceModule = "OpenSim.Services.Connectors.dll:MapImageServicesConnector"

[LibraryService]
    LocalServiceModule = "OpenSim.Services.InventoryService.dll:LibraryService"
    LibraryName = "Fresh Metaverse Library"
    DefaultLibrary = "{{INVENTORY_DIR}}/Libraries.xml"

[Groups]
    Enabled = true
    Module = "Groups Module V2"
    NoticesEnabled = true
    MessagingModule = "Groups Messaging Module V2"
    MessagingEnabled = true
    MessageOnlineUsersOnly = true
    ServicesConnectorModule = "Groups HG Service Connector"
    GroupsServerURI = "http://127.0.0.1:{{PRIVATE_PORT}}"
    GroupsExternalURI = "${Const|BaseURL}:${Const|PublicPort}"
    LocalService = remote
    HomeURI = "${Const|BaseURL}:${Const|PublicPort}"

[Messaging]
    MessageTransferModule = HGMessageTransferModule
    LureModule = HGLureModule
    Gatekeeper = "${Const|BaseURL}:${Const|PublicPort}"
	OfflineMessageModule = "Offline Message Module V2"
    OfflineMessageURL = "http://127.0.0.1:{{PRIVATE_PORT}}"
	MuteListModule = MuteListModule
    ConferenceTraceEnabled = true
[Wind]
    enabled = true
    wind_update_rate = 150
    wind_plugin = SimpleRandomWind
    avg_strength = 5.0
    avg_direction = 0.0
    var_strength = 5.0
    var_direction = 30.0
    rate_change = 1.0
    strength = 1.0

[HGInstantMessageService]
    LocalServiceModule = "OpenSim.Services.HypergridService.dll:HGInstantMessageService"
    GridService = "OpenSim.Services.Connectors.dll:GridServicesConnector"
    PresenceService = "OpenSim.Services.Connectors.dll:PresenceServicesConnector"
    UserAgentService = "OpenSim.Services.Connectors.dll:UserAgentServiceConnector"

;; ---------------------------------------------------------------------------
;;  QUIC transport per-region (fixed native listener port per region)
;;  AdvertiseHost + Port feed RegionInfo.QuicHost/QuicPort, which the grid
;;  database stores at sim startup — that is what login/teleport/neighbour
;;  events advertise to viewers for direct native connections. Keep them
;;  accurate; never derive ports with arithmetic here.
;; ---------------------------------------------------------------------------

[ClientStack.Quic]
    Enabled = true
    Port = {{QUIC_PORT}}
    AdvertiseHost = "{{REGION_HOST}}"
    ALPN = opensim-ll/1
    ProxyRegistrationURL = http://127.0.0.1:{{PRIVATE_PORT}}/admin/quic/circuit
    BrainURL = http://127.0.0.1:{{QUICKG_BRAIN_PORT}}
    BrainPort = {{QUICKG_BRAIN_PORT}}
    BrainHeartbeatSeconds = {{QUIC_HEARTBEAT_SECONDS}}
    CertificatePath = "{{QUIC_CERT_PEM_PATH}}"
    PrivateKeyPath = "{{QUIC_KEY_PEM_PATH}}"
    AllowLegacyLLUDP = true

;; ---------------------------------------------------------------------------
;;  HG authorization — local Python auth endpoint
;; ---------------------------------------------------------------------------

[AuthorizationService]
    AuthorizationServerURI = "http://127.0.0.1:{{HG_AUTH_PORT}}/hg/auth"
    ResponseOnFailure = false

;; ---------------------------------------------------------------------------
;;  HG inventory access — allow hypergrid visitors full inventory
;; ---------------------------------------------------------------------------

[HGInventoryAccessModule]
    RestrictInventoryAccessAbroad = False

;; ---------------------------------------------------------------------------
;;  Hypergrid
;; ---------------------------------------------------------------------------

[Hypergrid]
    HomeURI = "${Const|BaseURL}:${Const|PublicPort}"
    GatekeeperURI = "${Const|BaseURL}:${Const|PublicPort}"

;; ---------------------------------------------------------------------------
;;  Flotsam asset cache
;; ---------------------------------------------------------------------------

[FlotsamAssetCache]
    CacheDirectory = "{{ASSETCACHE_DIR}}"
    CacheDirectoryOptional = true
    FileTimeout = 5000
    FileRetryCount = 3
    CacheType = 1
    MaxCacheFiles = 0
    MinCacheFiles = 0

;; ---------------------------------------------------------------------------
;;  Estate data — local (per-sim)
;; ---------------------------------------------------------------------------

[EstateDataStore]
    LocalServiceModule = "OpenSim.Services.EstateService.dll:EstateDataService"
    StorageProvider = "OpenSim.Data.{{DB_PROVIDER}}.dll"
    ConnectionString = "{{SIM_DB_CONN}}"

[SimulationDataStore]
    LocalServiceModule = "OpenSim.Services.SimulationService.dll:SimulationDataService"
    StorageProvider = "OpenSim.Data.{{DB_PROVIDER}}.dll"
    ConnectionString = "{{SIM_DB_CONN}}"

;; ---------------------------------------------------------------------------
;;  Physics
;; ---------------------------------------------------------------------------

[ODEPhysicsSettings]
    AvatarTerminationTime = 10

[BulletSim]
    ;; Placeholder section — filled with parameters when physics=BulletSim.
[Map]
    GenerateMaptiles = true
    MapImageModule = "MapImageModule"
    ; MaptileRefresh = 0
    ; MaptileStaticUUID = "00000000-0000-0000-0000-000000000000"
    ; TextureOnMapTile = true
    ; DrawPrimOnMapTile = true
    ; TexturePrims = true
    ; TexturePrimSize = 48
    ; RenderMeshes = false
    ; MapColorWater = "#3399FF"
    ; MapColor1 = "#A58976"
    ; MapColor2 = "#455931"
    ; MapColor3 = "#A29A8D"
    ; MapColor4 = "#C8C8C8"

[Permissions]
    permissionmodules =  DefaultPermissionsModule, PrimLimitsModule
    ; serverside_object_permissions = true
    automatic_gods = false
    implicit_gods = false
    allow_grid_gods = true
    region_owner_is_god = true
    region_manager_is_god = true
    ; simple_build_permissions = false
[Experience]
     Enabled = true
[NPC]
    Enabled = true
    MaxNumberNPCsPerScene = 120
    AllowNotOwned = true
    AllowSenseAsAvatar = true
    AllowCloneOtherAvatars = false
    NoNPCGroup = true
[Economy]
    ;; Local Dorito economy via tasia-moneyd (PGSQL, port 1026)
    ;; Auto-started alongside Robust; see H:/grid/moneyd/MoneyServer.ini
    SellEnabled = true
    EconomyModule = DTLNSLMoneyModule
    CurrencyServer = "http://127.0.0.1:1026/"
    UserServer = "${Const|BaseURL}:${Const|PublicPort}/"
    CheckServerCert = false
    PriceUpload = 0
    MeshModelUploadCostFactor = 1.0
    MeshModelUploadTextureCostFactor = 1.0
    MeshModelMinCostFactor = 1.0
    PriceGroupCreate = 0
    ObjectCount = 0
    PriceEnergyUnit = 0
    PriceObjectClaim = 0
    PricePublicObjectDecay = 0
    PricePublicObjectDelete = 0
    PriceParcelClaim = 0
    PriceParcelClaimFactor = 1
    PriceRentLight = 0
    TeleportMinPrice = 0
    TeleportPriceExponent = 2
    EnergyEfficiency = 1
    PriceObjectRent = 0
    PriceObjectScaleFactor = 10
    PriceParcelRent = 0
[UserProfiles]
    ; ProfileServiceURL is THE key the sim module reads (missing = module
    ; silently disabled = profile requests never fire). ProfileURL kept
    ; identical for any other consumer.
    ProfileServiceURL = "${Const|BaseURL}:${Const|PublicPort}"
    ProfileURL = "${Const|BaseURL}:${Const|PublicPort}"
    ; AllowUserProfileWebURLs = true
[XBakes]
    ; Disabled until a bakes service is deployed. Leaving this URL enabled
    ; causes post-movement 404/null-reference errors during world load.
    ; URL = ${Const|BaseURL}:${Const|PublicPort}

[OSSL]
    Include-osslDefaultEnable = "osslDefaultEnable.ini"
;; ---------------------------------------------------------------------------
;;  Region
;; ---------------------------------------------------------------------------

;; Region definitions are loaded from ./regions/*.ini via [Startup]
;; regionload_regionsdir. No [Region] section here.
