<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>TasiaAddons.LoginSecurity</AssemblyName>
    <RootNamespace>TasiaAddons.LoginSecurity</RootNamespace>
    <Company>Tasia Extensions</Company>
    <Product>Tasia Addons - Login Security</Product>
    <Version>1.0.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="log4net">
      <HintPath>$(SolutionDir)/bin/log4net.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenSim.Framework">
      <HintPath>$(SolutionDir)/bin/OpenSim.Framework.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenSim.Services.Base">
      <HintPath>$(SolutionDir)/bin/OpenSim.Services.Base.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenSim.Services.Interfaces">
      <HintPath>$(SolutionDir)/bin/OpenSim.Services.Interfaces.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenSim.Region.Framework">
      <HintPath>$(SolutionDir)/bin/OpenSim.Region.Framework.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenSim.Data">
      <HintPath>$(SolutionDir)/bin/OpenSim.Data.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../Source/Tasia.Extensions.SDK/Tasia.Extensions.SDK.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="xmlrpc" HintPath="..\..\Library\xmlrpc.dll" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Source\OpenSim.Data\OpenSim.Data.csproj" Private="false" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Source\OpenSim.Framework\OpenSim.Framework.csproj" Private="false" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Source\OpenSim.Region.Framework\OpenSim.Region.Framework.csproj" Private="false" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Source\OpenSim.Services.Base\OpenSim.Services.Base.csproj" Private="false" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Source\OpenSim.Services.Interfaces\OpenSim.Services.Interfaces.csproj" Private="false" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="log4net" Version="3.3.2" />
  </ItemGroup>
</Project>
