<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyTitle>OpenSimMuteList.Modules</AssemblyTitle>
    <Product>OpenSim</Product>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="xmlrpc" HintPath="..\..\Library\xmlrpc.dll" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Source\OpenSim.Framework\OpenSim.Framework.csproj" Private="false" />
    <ProjectReference Include="..\..\Source\OpenSim.Region.Framework\OpenSim.Region.Framework.csproj" Private="false" />
    <ProjectReference Include="..\..\Source\OpenSim.Services.Interfaces\OpenSim.Services.Interfaces.csproj" Private="false" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.10" />
  </ItemGroup>
  
</Project>
