//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:/legion-grid-source/OpenSim/Addons/Phlox/grammar/Assembler.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="AssemblerParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IAssemblerVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="AssemblerParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] AssemblerParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AssemblerParser.globals"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGlobals([NotNull] AssemblerParser.GlobalsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AssemblerParser.functionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionDeclaration([NotNull] AssemblerParser.FunctionDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AssemblerParser.eventHandlerDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEventHandlerDecl([NotNull] AssemblerParser.EventHandlerDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AssemblerParser.stateDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStateDecl([NotNull] AssemblerParser.StateDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AssemblerParser.instr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstr([NotNull] AssemblerParser.InstrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AssemblerParser.operand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperand([NotNull] AssemblerParser.OperandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AssemblerParser.label_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabel_([NotNull] AssemblerParser.Label_Context context);
}
