//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:/legion-grid-source/OpenSim/Addons/Phlox/grammar/Assembler.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;
using InWorldz.Phlox.ByteCompiler;
using InWorldz.Phlox.Types;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class AssemblerParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, STATE_ID=11, VECTOR=12, ROTATION=13, REG=14, ID=15, FUNC=16, 
		INT=17, STRING=18, FLOAT=19, WS=20, NEWLINE=21;
	public const int
		RULE_program = 0, RULE_globals = 1, RULE_functionDeclaration = 2, RULE_eventHandlerDecl = 3, 
		RULE_stateDecl = 4, RULE_instr = 5, RULE_operand = 6, RULE_label_ = 7;
	public static readonly string[] ruleNames = {
		"program", "globals", "functionDeclaration", "eventHandlerDecl", "stateDecl", 
		"instr", "operand", "label_"
	};

	private static readonly string[] _LiteralNames = {
		null, "'.globals'", "'.def'", "':'", "'args'", "'='", "','", "'locals'", 
		"'.evt'", "'/'", "'.statedef'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, "STATE_ID", 
		"VECTOR", "ROTATION", "REG", "ID", "FUNC", "INT", "STRING", "FLOAT", "WS", 
		"NEWLINE"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Assembler.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static AssemblerParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}


	    private BytecodeGenerator _bytecodeGen;

	    public void SetGenerator(BytecodeGenerator bcg) { _bytecodeGen = bcg; }

	    protected void Gen(Antlr4.Runtime.IToken instrToken)
	        { _bytecodeGen.Gen(instrToken); }

	    protected void Gen(Antlr4.Runtime.IToken instrToken, Antlr4.Runtime.IToken operandToken)
	        { _bytecodeGen.Gen(instrToken, operandToken); }

	    protected void Gen(Antlr4.Runtime.IToken instrToken, Antlr4.Runtime.IToken oToken1, Antlr4.Runtime.IToken oToken2)
	        { _bytecodeGen.Gen(instrToken, oToken1, oToken2); }

	    protected void Gen(Antlr4.Runtime.IToken instrToken, Antlr4.Runtime.IToken oToken1, Antlr4.Runtime.IToken oToken2, Antlr4.Runtime.IToken oToken3)
	        { _bytecodeGen.Gen(instrToken, oToken1, oToken2, oToken3); }

	    protected void CheckForUnresolvedReferences()
	        { _bytecodeGen.CheckForUnresolvedReferences(); }

	    protected void DefineFunction(Antlr4.Runtime.IToken idToken, int nargs, int nlocals)
	        { _bytecodeGen.DefineFunction(idToken, nargs, nlocals); }

	    protected void DefineEventHandler(Antlr4.Runtime.IToken stateIdToken, Antlr4.Runtime.IToken idToken, int nargs, int nlocals)
	        { _bytecodeGen.DefineEventHandler(stateIdToken, idToken, nargs, nlocals); }

	    protected void DefineDataSize(int n)
	        { _bytecodeGen.DefineDataSize(n); }

	    protected void DefineLabel(Antlr4.Runtime.IToken idToken)
	        { _bytecodeGen.DefineLabel(idToken); }

	    protected void DefineState(Antlr4.Runtime.IToken stateId)
	        { _bytecodeGen.DefineState(stateId); }

		public AssemblerParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public AssemblerParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgramContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public GlobalsContext globals() {
			return GetRuleContext<GlobalsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionDeclarationContext[] functionDeclaration() {
			return GetRuleContexts<FunctionDeclarationContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionDeclarationContext functionDeclaration(int i) {
			return GetRuleContext<FunctionDeclarationContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public EventHandlerDeclContext[] eventHandlerDecl() {
			return GetRuleContexts<EventHandlerDeclContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public EventHandlerDeclContext eventHandlerDecl(int i) {
			return GetRuleContext<EventHandlerDeclContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StateDeclContext[] stateDecl() {
			return GetRuleContexts<StateDeclContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StateDeclContext stateDecl(int i) {
			return GetRuleContext<StateDeclContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public InstrContext[] instr() {
			return GetRuleContexts<InstrContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public InstrContext instr(int i) {
			return GetRuleContext<InstrContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Label_Context[] label_() {
			return GetRuleContexts<Label_Context>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Label_Context label_(int i) {
			return GetRuleContext<Label_Context>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] NEWLINE() { return GetTokens(AssemblerParser.NEWLINE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NEWLINE(int i) {
			return GetToken(AssemblerParser.NEWLINE, i);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IAssemblerListener typedListener = listener as IAssemblerListener;
			if (typedListener != null) typedListener.EnterProgram(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IAssemblerListener typedListener = listener as IAssemblerListener;
			if (typedListener != null) typedListener.ExitProgram(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAssemblerVisitor<TResult> typedVisitor = visitor as IAssemblerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProgram(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 17;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,0,Context) ) {
			case 1:
				{
				State = 16;
				globals();
				}
				break;
			}
			State = 25;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				State = 25;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,1,Context) ) {
				case 1:
					{
					State = 19;
					functionDeclaration();
					}
					break;
				case 2:
					{
					State = 20;
					eventHandlerDecl();
					}
					break;
				case 3:
					{
					State = 21;
					stateDecl();
					}
					break;
				case 4:
					{
					State = 22;
					instr();
					}
					break;
				case 5:
					{
					State = 23;
					label_();
					}
					break;
				case 6:
					{
					State = 24;
					Match(NEWLINE);
					}
					break;
				}
				}
				State = 27;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & 2131204L) != 0) );
			 CheckForUnresolvedReferences(); 
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class GlobalsContext : ParserRuleContext {
		public IToken _INT;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT() { return GetToken(AssemblerParser.INT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] NEWLINE() { return GetTokens(AssemblerParser.NEWLINE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NEWLINE(int i) {
			return GetToken(AssemblerParser.NEWLINE, i);
		}
		public GlobalsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_globals; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IAssemblerListener typedListener = listener as IAssemblerListener;
			if (typedListener != null) typedListener.EnterGlobals(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IAssemblerListener typedListener = listener as IAssemblerListener;
			if (typedListener != null) typedListener.ExitGlobals(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAssemblerVisitor<TResult> typedVisitor = visitor as IAssemblerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitGlobals(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public GlobalsContext globals() {
		GlobalsContext _localctx = new GlobalsContext(Context, State);
		EnterRule(_localctx, 2, RULE_globals);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 34;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==NEWLINE) {
				{
				{
				State = 31;
				Match(NEWLINE);
				}
				}
				State = 36;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 37;
			Match(T__0);
			State = 38;
			_localctx._INT = Match(INT);
			State = 39;
			Match(NEWLINE);
			 DefineDataSize(int.Parse((_localctx._INT!=null?_localctx._INT.Text:null))); 
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionDeclarationContext : ParserRuleContext {
		public IToken name;
		public IToken a;
		public IToken lo;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NEWLINE() { return GetToken(AssemblerParser.NEWLINE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(AssemblerParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] INT() { return GetTokens(AssemblerParser.INT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT(int i) {
			return GetToken(AssemblerParser.INT, i);
		}
		public FunctionDeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionDeclaration; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IAssemblerListener typedListener = listener as IAssemblerListener;
			if (typedListener != null) typedListener.EnterFunctionDeclaration(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IAssemblerListener typedListener = listener as IAssemblerListener;
			if (typedListener != null) typedListener.ExitFunctionDeclaration(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAssemblerVisitor<TResult> typedVisitor = visitor as IAssemblerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionDeclaration(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionDeclarationContext functionDeclaration() {
		FunctionDeclarationContext _localctx = new FunctionDeclarationContext(Context, State);
		EnterRule(_localctx, 4, RULE_functionDeclaration);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 42;
			Match(T__1);
			State = 43;
			_localctx.name = Match(ID);
			State = 44;
			Match(T__2);
			State = 45;
			Match(T__3);
			State = 46;
			Match(T__4);
			State = 47;
			_localctx.a = Match(INT);
			State = 48;
			Match(T__5);
			State = 49;
			Match(T__6);
			State = 50;
			Match(T__4);
			State = 51;
			_localctx.lo = Match(INT);
			State = 52;
			Match(NEWLINE);
			 DefineFunction(_localctx.name, int.Parse((_localctx.a!=null?_localctx.a.Text:null)), int.Parse((_localctx.lo!=null?_localctx.lo.Text:null))); 
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EventHandlerDeclContext : ParserRuleContext {
		public IToken state;
		public IToken name;
		public IToken a;
		public IToken lo;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NEWLINE() { return GetToken(AssemblerParser.NEWLINE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] ID() { return GetTokens(AssemblerParser.ID); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID(int i) {
			return GetToken(AssemblerParser.ID, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] INT() { return GetTokens(AssemblerParser.INT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT(int i) {
			return GetToken(AssemblerParser.INT, i);
		}
		public EventHandlerDeclContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_eventHandlerDecl; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IAssemblerListener typedListener = listener as IAssemblerListener;
			if (typedListener != null) typedListener.EnterEventHandlerDecl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IAssemblerListener typedListener = listener as IAssemblerListener;
			if (typedListener != null) typedListener.ExitEventHandlerDecl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAssemblerVisitor<TResult> typedVisitor = visitor as IAssemblerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEventHandlerDecl(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public EventHandlerDeclContext eventHandlerDecl() {
		EventHandlerDeclContext _localctx = new EventHandlerDeclContext(Context, State);
		EnterRule(_localctx, 6, RULE_eventHandlerDecl);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 55;
			Match(T__7);
			State = 56;
			_localctx.state = Match(ID);
			State = 57;
			Match(T__8);
			State = 58;
			_localctx.name = Match(ID);
			State = 59;
			Match(T__2);
			State = 60;
			Match(T__3);
			State = 61;
			Match(T__4);
			State = 62;
			_localctx.a = Match(INT);
			State = 63;
			Match(T__5);
			State = 64;
			Match(T__6);
			State = 65;
			Match(T__4);
			State = 66;
			_localctx.lo = Match(INT);
			State = 67;
			Match(NEWLINE);
			 DefineEventHandler(_localctx.state, _localctx.name, int.Parse((_localctx.a!=null?_localctx.a.Text:null)), int.Parse((_localctx.lo!=null?_localctx.lo.Text:null))); 
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StateDeclContext : ParserRuleContext {
		public IToken name;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NEWLINE() { return GetToken(AssemblerParser.NEWLINE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(AssemblerParser.ID, 0); }
		public StateDeclContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stateDecl; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IAssemblerListener typedListener = listener as IAssemblerListener;
			if (typedListener != null) typedListener.EnterStateDecl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IAssemblerListener typedListener = listener as IAssemblerListener;
			if (typedListener != null) typedListener.ExitStateDecl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAssemblerVisitor<TResult> typedVisitor = visitor as IAssemblerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStateDecl(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StateDeclContext stateDecl() {
		StateDeclContext _localctx = new StateDeclContext(Context, State);
		EnterRule(_localctx, 8, RULE_stateDecl);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 70;
			Match(T__9);
			State = 71;
			_localctx.name = Match(ID);
			State = 72;
			Match(NEWLINE);
			 DefineState(_localctx.name); 
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class InstrContext : ParserRuleContext {
		public IToken _ID;
		public OperandContext _operand;
		public OperandContext a;
		public OperandContext b;
		public OperandContext c;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(AssemblerParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NEWLINE() { return GetToken(AssemblerParser.NEWLINE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public OperandContext[] operand() {
			return GetRuleContexts<OperandContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public OperandContext operand(int i) {
			return GetRuleContext<OperandContext>(i);
		}
		public InstrContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_instr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IAssemblerListener typedListener = listener as IAssemblerListener;
			if (typedListener != null) typedListener.EnterInstr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IAssemblerListener typedListener = listener as IAssemblerListener;
			if (typedListener != null) typedListener.ExitInstr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAssemblerVisitor<TResult> typedVisitor = visitor as IAssemblerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInstr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public InstrContext instr() {
		InstrContext _localctx = new InstrContext(Context, State);
		EnterRule(_localctx, 10, RULE_instr);
		try {
			State = 99;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 75;
				_localctx._ID = Match(ID);
				State = 76;
				Match(NEWLINE);
				 Gen(_localctx._ID); 
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 78;
				_localctx._ID = Match(ID);
				State = 79;
				_localctx._operand = operand();
				State = 80;
				Match(NEWLINE);
				 Gen(_localctx._ID, (_localctx._operand!=null?(_localctx._operand.Start):null)); 
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 83;
				_localctx._ID = Match(ID);
				State = 84;
				_localctx.a = operand();
				State = 85;
				Match(T__5);
				State = 86;
				_localctx.b = operand();
				State = 87;
				Match(NEWLINE);
				 Gen(_localctx._ID, (_localctx.a!=null?(_localctx.a.Start):null), (_localctx.b!=null?(_localctx.b.Start):null)); 
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 90;
				_localctx._ID = Match(ID);
				State = 91;
				_localctx.a = operand();
				State = 92;
				Match(T__5);
				State = 93;
				_localctx.b = operand();
				State = 94;
				Match(T__5);
				State = 95;
				_localctx.c = operand();
				State = 96;
				Match(NEWLINE);
				 Gen(_localctx._ID, (_localctx.a!=null?(_localctx.a.Start):null), (_localctx.b!=null?(_localctx.b.Start):null), (_localctx.c!=null?(_localctx.c.Start):null)); 
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OperandContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(AssemblerParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode REG() { return GetToken(AssemblerParser.REG, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FUNC() { return GetToken(AssemblerParser.FUNC, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT() { return GetToken(AssemblerParser.INT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(AssemblerParser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VECTOR() { return GetToken(AssemblerParser.VECTOR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ROTATION() { return GetToken(AssemblerParser.ROTATION, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FLOAT() { return GetToken(AssemblerParser.FLOAT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STATE_ID() { return GetToken(AssemblerParser.STATE_ID, 0); }
		public OperandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_operand; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IAssemblerListener typedListener = listener as IAssemblerListener;
			if (typedListener != null) typedListener.EnterOperand(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IAssemblerListener typedListener = listener as IAssemblerListener;
			if (typedListener != null) typedListener.ExitOperand(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAssemblerVisitor<TResult> typedVisitor = visitor as IAssemblerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOperand(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OperandContext operand() {
		OperandContext _localctx = new OperandContext(Context, State);
		EnterRule(_localctx, 12, RULE_operand);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 101;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 1046528L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Label_Context : ParserRuleContext {
		public IToken _ID;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(AssemblerParser.ID, 0); }
		public Label_Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_label_; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IAssemblerListener typedListener = listener as IAssemblerListener;
			if (typedListener != null) typedListener.EnterLabel_(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IAssemblerListener typedListener = listener as IAssemblerListener;
			if (typedListener != null) typedListener.ExitLabel_(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAssemblerVisitor<TResult> typedVisitor = visitor as IAssemblerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLabel_(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Label_Context label_() {
		Label_Context _localctx = new Label_Context(Context, State);
		EnterRule(_localctx, 14, RULE_label_);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 103;
			_localctx._ID = Match(ID);
			State = 104;
			Match(T__2);
			 DefineLabel(_localctx._ID); 
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,21,108,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,1,0,3,0,18,8,0,1,0,1,0,1,0,1,0,1,0,1,0,4,0,26,8,0,11,0,12,0,27,1,0,
		1,0,1,1,5,1,33,8,1,10,1,12,1,36,9,1,1,1,1,1,1,1,1,1,1,1,1,2,1,2,1,2,1,
		2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,
		1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,4,1,4,1,4,1,4,1,4,1,5,1,5,1,5,1,5,1,5,1,
		5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,
		1,5,3,5,100,8,5,1,6,1,6,1,7,1,7,1,7,1,7,1,7,0,0,8,0,2,4,6,8,10,12,14,0,
		1,1,0,11,19,110,0,17,1,0,0,0,2,34,1,0,0,0,4,42,1,0,0,0,6,55,1,0,0,0,8,
		70,1,0,0,0,10,99,1,0,0,0,12,101,1,0,0,0,14,103,1,0,0,0,16,18,3,2,1,0,17,
		16,1,0,0,0,17,18,1,0,0,0,18,25,1,0,0,0,19,26,3,4,2,0,20,26,3,6,3,0,21,
		26,3,8,4,0,22,26,3,10,5,0,23,26,3,14,7,0,24,26,5,21,0,0,25,19,1,0,0,0,
		25,20,1,0,0,0,25,21,1,0,0,0,25,22,1,0,0,0,25,23,1,0,0,0,25,24,1,0,0,0,
		26,27,1,0,0,0,27,25,1,0,0,0,27,28,1,0,0,0,28,29,1,0,0,0,29,30,6,0,-1,0,
		30,1,1,0,0,0,31,33,5,21,0,0,32,31,1,0,0,0,33,36,1,0,0,0,34,32,1,0,0,0,
		34,35,1,0,0,0,35,37,1,0,0,0,36,34,1,0,0,0,37,38,5,1,0,0,38,39,5,17,0,0,
		39,40,5,21,0,0,40,41,6,1,-1,0,41,3,1,0,0,0,42,43,5,2,0,0,43,44,5,15,0,
		0,44,45,5,3,0,0,45,46,5,4,0,0,46,47,5,5,0,0,47,48,5,17,0,0,48,49,5,6,0,
		0,49,50,5,7,0,0,50,51,5,5,0,0,51,52,5,17,0,0,52,53,5,21,0,0,53,54,6,2,
		-1,0,54,5,1,0,0,0,55,56,5,8,0,0,56,57,5,15,0,0,57,58,5,9,0,0,58,59,5,15,
		0,0,59,60,5,3,0,0,60,61,5,4,0,0,61,62,5,5,0,0,62,63,5,17,0,0,63,64,5,6,
		0,0,64,65,5,7,0,0,65,66,5,5,0,0,66,67,5,17,0,0,67,68,5,21,0,0,68,69,6,
		3,-1,0,69,7,1,0,0,0,70,71,5,10,0,0,71,72,5,15,0,0,72,73,5,21,0,0,73,74,
		6,4,-1,0,74,9,1,0,0,0,75,76,5,15,0,0,76,77,5,21,0,0,77,100,6,5,-1,0,78,
		79,5,15,0,0,79,80,3,12,6,0,80,81,5,21,0,0,81,82,6,5,-1,0,82,100,1,0,0,
		0,83,84,5,15,0,0,84,85,3,12,6,0,85,86,5,6,0,0,86,87,3,12,6,0,87,88,5,21,
		0,0,88,89,6,5,-1,0,89,100,1,0,0,0,90,91,5,15,0,0,91,92,3,12,6,0,92,93,
		5,6,0,0,93,94,3,12,6,0,94,95,5,6,0,0,95,96,3,12,6,0,96,97,5,21,0,0,97,
		98,6,5,-1,0,98,100,1,0,0,0,99,75,1,0,0,0,99,78,1,0,0,0,99,83,1,0,0,0,99,
		90,1,0,0,0,100,11,1,0,0,0,101,102,7,0,0,0,102,13,1,0,0,0,103,104,5,15,
		0,0,104,105,5,3,0,0,105,106,6,7,-1,0,106,15,1,0,0,0,5,17,25,27,34,99
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
