//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:/legion-grid-source/OpenSim/Addons/Phlox/grammar/Assembler.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IAssemblerListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class AssemblerBaseListener : IAssemblerListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="AssemblerParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] AssemblerParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AssemblerParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] AssemblerParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AssemblerParser.globals"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGlobals([NotNull] AssemblerParser.GlobalsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AssemblerParser.globals"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGlobals([NotNull] AssemblerParser.GlobalsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AssemblerParser.functionDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionDeclaration([NotNull] AssemblerParser.FunctionDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AssemblerParser.functionDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionDeclaration([NotNull] AssemblerParser.FunctionDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AssemblerParser.eventHandlerDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEventHandlerDecl([NotNull] AssemblerParser.EventHandlerDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AssemblerParser.eventHandlerDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEventHandlerDecl([NotNull] AssemblerParser.EventHandlerDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AssemblerParser.stateDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStateDecl([NotNull] AssemblerParser.StateDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AssemblerParser.stateDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStateDecl([NotNull] AssemblerParser.StateDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AssemblerParser.instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstr([NotNull] AssemblerParser.InstrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AssemblerParser.instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstr([NotNull] AssemblerParser.InstrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AssemblerParser.operand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperand([NotNull] AssemblerParser.OperandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AssemblerParser.operand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperand([NotNull] AssemblerParser.OperandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AssemblerParser.label_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLabel_([NotNull] AssemblerParser.Label_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AssemblerParser.label_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLabel_([NotNull] AssemblerParser.Label_Context context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
