<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>TasiaAddons.RestartModule</AssemblyName>
    <RootNamespace>TasiaAddons.RestartModule</RootNamespace>
    <Company>Tasia Extensions</Company>
    <Product>Tasia Addons - Restart Module</Product>
    <Version>1.0.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="log4net">
      <HintPath>$(SolutionDir)/bin/log4net.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Nini">
      <HintPath>$(SolutionDir)/bin/Nini.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenMetaverse">
      <HintPath>$(SolutionDir)/bin/OpenMetaverse.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenMetaverseTypes">
      <HintPath>$(SolutionDir)/bin/OpenMetaverseTypes.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenMetaverse.StructuredData">
      <HintPath>$(SolutionDir)/bin/OpenMetaverse.StructuredData.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenSim.Framework">
      <HintPath>$(SolutionDir)/bin/OpenSim.Framework.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenSim.Framework.Console">
      <HintPath>$(SolutionDir)/bin/OpenSim.Framework.Console.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenSim.Framework.Servers">
      <HintPath>$(SolutionDir)/bin/OpenSim.Framework.Servers.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenSim.Framework.Servers.HttpServer">
      <HintPath>$(SolutionDir)/bin/OpenSim.Framework.Servers.HttpServer.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenSim.Region.Framework">
      <HintPath>$(SolutionDir)/bin/OpenSim.Region.Framework.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenSim.Region.Framework.Interfaces">
      <HintPath>$(SolutionDir)/bin/OpenSim.Region.Framework.Interfaces.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenSim.Services.Interfaces">
      <HintPath>$(SolutionDir)/bin/OpenSim.Services.Interfaces.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="$(SolutionDir)/Source/Tasia.Extensions.SDK/Tasia.Extensions.SDK.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Mono.Addins" Version="1.4.1" />
  </ItemGroup>
</Project>
