//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:/legion-grid-source/OpenSim/Addons/Phlox/grammar/LSL.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ILSLListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class LSLBaseListener : ILSLParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="LSLParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProg([NotNull] LSLParser.ProgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LSLParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProg([NotNull] LSLParser.ProgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LSLParser.globalStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGlobalStmt([NotNull] LSLParser.GlobalStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LSLParser.globalStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGlobalStmt([NotNull] LSLParser.GlobalStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>namedStateDef</c>
	/// labeled alternative in <see cref="LSLParser.stateDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamedStateDef([NotNull] LSLParser.NamedStateDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>namedStateDef</c>
	/// labeled alternative in <see cref="LSLParser.stateDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamedStateDef([NotNull] LSLParser.NamedStateDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>defaultStateDef</c>
	/// labeled alternative in <see cref="LSLParser.stateDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefaultStateDef([NotNull] LSLParser.DefaultStateDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>defaultStateDef</c>
	/// labeled alternative in <see cref="LSLParser.stateDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefaultStateDef([NotNull] LSLParser.DefaultStateDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LSLParser.stateBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStateBlock([NotNull] LSLParser.StateBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LSLParser.stateBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStateBlock([NotNull] LSLParser.StateBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LSLParser.stateBlockContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStateBlockContent([NotNull] LSLParser.StateBlockContentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LSLParser.stateBlockContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStateBlockContent([NotNull] LSLParser.StateBlockContentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LSLParser.funcDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncDef([NotNull] LSLParser.FuncDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LSLParser.funcDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncDef([NotNull] LSLParser.FuncDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LSLParser.funcBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncBlock([NotNull] LSLParser.FuncBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LSLParser.funcBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncBlock([NotNull] LSLParser.FuncBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LSLParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] LSLParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LSLParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] LSLParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LSLParser.exprStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprStatement([NotNull] LSLParser.ExprStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LSLParser.exprStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprStatement([NotNull] LSLParser.ExprStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LSLParser.label_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLabel_([NotNull] LSLParser.Label_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LSLParser.label_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLabel_([NotNull] LSLParser.Label_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>semiStmt</c>
	/// labeled alternative in <see cref="LSLParser.funcBlockContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSemiStmt([NotNull] LSLParser.SemiStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>semiStmt</c>
	/// labeled alternative in <see cref="LSLParser.funcBlockContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSemiStmt([NotNull] LSLParser.SemiStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>assignmentStmt</c>
	/// labeled alternative in <see cref="LSLParser.funcBlockContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignmentStmt([NotNull] LSLParser.AssignmentStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>assignmentStmt</c>
	/// labeled alternative in <see cref="LSLParser.funcBlockContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignmentStmt([NotNull] LSLParser.AssignmentStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ifStmt</c>
	/// labeled alternative in <see cref="LSLParser.funcBlockContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStmt([NotNull] LSLParser.IfStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ifStmt</c>
	/// labeled alternative in <see cref="LSLParser.funcBlockContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStmt([NotNull] LSLParser.IfStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>whileStmt</c>
	/// labeled alternative in <see cref="LSLParser.funcBlockContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileStmt([NotNull] LSLParser.WhileStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>whileStmt</c>
	/// labeled alternative in <see cref="LSLParser.funcBlockContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileStmt([NotNull] LSLParser.WhileStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>forStmt</c>
	/// labeled alternative in <see cref="LSLParser.funcBlockContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForStmt([NotNull] LSLParser.ForStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>forStmt</c>
	/// labeled alternative in <see cref="LSLParser.funcBlockContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForStmt([NotNull] LSLParser.ForStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>doWhileStmt</c>
	/// labeled alternative in <see cref="LSLParser.funcBlockContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDoWhileStmt([NotNull] LSLParser.DoWhileStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>doWhileStmt</c>
	/// labeled alternative in <see cref="LSLParser.funcBlockContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDoWhileStmt([NotNull] LSLParser.DoWhileStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>varDeclStmt</c>
	/// labeled alternative in <see cref="LSLParser.funcBlockContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarDeclStmt([NotNull] LSLParser.VarDeclStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>varDeclStmt</c>
	/// labeled alternative in <see cref="LSLParser.funcBlockContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarDeclStmt([NotNull] LSLParser.VarDeclStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>funcCallStmt</c>
	/// labeled alternative in <see cref="LSLParser.funcBlockContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncCallStmt([NotNull] LSLParser.FuncCallStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>funcCallStmt</c>
	/// labeled alternative in <see cref="LSLParser.funcBlockContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncCallStmt([NotNull] LSLParser.FuncCallStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>preIncrementStmt</c>
	/// labeled alternative in <see cref="LSLParser.funcBlockContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPreIncrementStmt([NotNull] LSLParser.PreIncrementStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>preIncrementStmt</c>
	/// labeled alternative in <see cref="LSLParser.funcBlockContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPreIncrementStmt([NotNull] LSLParser.PreIncrementStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>preDecrementStmt</c>
	/// labeled alternative in <see cref="LSLParser.funcBlockContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPreDecrementStmt([NotNull] LSLParser.PreDecrementStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>preDecrementStmt</c>
	/// labeled alternative in <see cref="LSLParser.funcBlockContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPreDecrementStmt([NotNull] LSLParser.PreDecrementStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>postIncrementStmt</c>
	/// labeled alternative in <see cref="LSLParser.funcBlockContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPostIncrementStmt([NotNull] LSLParser.PostIncrementStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>postIncrementStmt</c>
	/// labeled alternative in <see cref="LSLParser.funcBlockContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPostIncrementStmt([NotNull] LSLParser.PostIncrementStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>postDecrementStmt</c>
	/// labeled alternative in <see cref="LSLParser.funcBlockContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPostDecrementStmt([NotNull] LSLParser.PostDecrementStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>postDecrementStmt</c>
	/// labeled alternative in <see cref="LSLParser.funcBlockContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPostDecrementStmt([NotNull] LSLParser.PostDecrementStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>returnStmt</c>
	/// labeled alternative in <see cref="LSLParser.funcBlockContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnStmt([NotNull] LSLParser.ReturnStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>returnStmt</c>
	/// labeled alternative in <see cref="LSLParser.funcBlockContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnStmt([NotNull] LSLParser.ReturnStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>stateChangeStmt</c>
	/// labeled alternative in <see cref="LSLParser.funcBlockContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStateChangeStmt([NotNull] LSLParser.StateChangeStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>stateChangeStmt</c>
	/// labeled alternative in <see cref="LSLParser.funcBlockContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStateChangeStmt([NotNull] LSLParser.StateChangeStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>labelStmt</c>
	/// labeled alternative in <see cref="LSLParser.funcBlockContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLabelStmt([NotNull] LSLParser.LabelStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>labelStmt</c>
	/// labeled alternative in <see cref="LSLParser.funcBlockContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLabelStmt([NotNull] LSLParser.LabelStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>jumpStmt</c>
	/// labeled alternative in <see cref="LSLParser.funcBlockContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJumpStmt([NotNull] LSLParser.JumpStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>jumpStmt</c>
	/// labeled alternative in <see cref="LSLParser.funcBlockContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJumpStmt([NotNull] LSLParser.JumpStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>anonBlock</c>
	/// labeled alternative in <see cref="LSLParser.funcBlockContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnonBlock([NotNull] LSLParser.AnonBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>anonBlock</c>
	/// labeled alternative in <see cref="LSLParser.funcBlockContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnonBlock([NotNull] LSLParser.AnonBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LSLParser.lhs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLhs([NotNull] LSLParser.LhsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LSLParser.lhs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLhs([NotNull] LSLParser.LhsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LSLParser.funcCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncCall([NotNull] LSLParser.FuncCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LSLParser.funcCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncCall([NotNull] LSLParser.FuncCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LSLParser.eventDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEventDef([NotNull] LSLParser.EventDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LSLParser.eventDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEventDef([NotNull] LSLParser.EventDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LSLParser.paramList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParamList([NotNull] LSLParser.ParamListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LSLParser.paramList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParamList([NotNull] LSLParser.ParamListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LSLParser.paramDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParamDecl([NotNull] LSLParser.ParamDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LSLParser.paramDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParamDecl([NotNull] LSLParser.ParamDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LSLParser.varDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarDecl([NotNull] LSLParser.VarDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LSLParser.varDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarDecl([NotNull] LSLParser.VarDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LSLParser.callParamList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCallParamList([NotNull] LSLParser.CallParamListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LSLParser.callParamList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCallParamList([NotNull] LSLParser.CallParamListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LSLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] LSLParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LSLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] LSLParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LSLParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] LSLParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LSLParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] LSLParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LSLParser.assignmentExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignmentExpression([NotNull] LSLParser.AssignmentExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LSLParser.assignmentExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignmentExpression([NotNull] LSLParser.AssignmentExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LSLParser.booleanExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBooleanExpression([NotNull] LSLParser.BooleanExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LSLParser.booleanExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBooleanExpression([NotNull] LSLParser.BooleanExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LSLParser.bitwiseExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBitwiseExpression([NotNull] LSLParser.BitwiseExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LSLParser.bitwiseExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBitwiseExpression([NotNull] LSLParser.BitwiseExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LSLParser.equalityExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEqualityExpression([NotNull] LSLParser.EqualityExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LSLParser.equalityExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEqualityExpression([NotNull] LSLParser.EqualityExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LSLParser.relationalExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelationalExpression([NotNull] LSLParser.RelationalExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LSLParser.relationalExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelationalExpression([NotNull] LSLParser.RelationalExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LSLParser.binaryBitwiseExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinaryBitwiseExpression([NotNull] LSLParser.BinaryBitwiseExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LSLParser.binaryBitwiseExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinaryBitwiseExpression([NotNull] LSLParser.BinaryBitwiseExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LSLParser.additiveExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdditiveExpression([NotNull] LSLParser.AdditiveExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LSLParser.additiveExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdditiveExpression([NotNull] LSLParser.AdditiveExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LSLParser.multiplicativeExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiplicativeExpression([NotNull] LSLParser.MultiplicativeExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LSLParser.multiplicativeExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiplicativeExpression([NotNull] LSLParser.MultiplicativeExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>unaryMinus</c>
	/// labeled alternative in <see cref="LSLParser.unaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryMinus([NotNull] LSLParser.UnaryMinusContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>unaryMinus</c>
	/// labeled alternative in <see cref="LSLParser.unaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryMinus([NotNull] LSLParser.UnaryMinusContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>unaryBoolNot</c>
	/// labeled alternative in <see cref="LSLParser.unaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryBoolNot([NotNull] LSLParser.UnaryBoolNotContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>unaryBoolNot</c>
	/// labeled alternative in <see cref="LSLParser.unaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryBoolNot([NotNull] LSLParser.UnaryBoolNotContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>unaryBitNot</c>
	/// labeled alternative in <see cref="LSLParser.unaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryBitNot([NotNull] LSLParser.UnaryBitNotContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>unaryBitNot</c>
	/// labeled alternative in <see cref="LSLParser.unaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryBitNot([NotNull] LSLParser.UnaryBitNotContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>typeCastExpr</c>
	/// labeled alternative in <see cref="LSLParser.unaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeCastExpr([NotNull] LSLParser.TypeCastExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>typeCastExpr</c>
	/// labeled alternative in <see cref="LSLParser.unaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeCastExpr([NotNull] LSLParser.TypeCastExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>typeCast</c>
	/// labeled alternative in <see cref="LSLParser.typeCastExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeCast([NotNull] LSLParser.TypeCastContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>typeCast</c>
	/// labeled alternative in <see cref="LSLParser.typeCastExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeCast([NotNull] LSLParser.TypeCastContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>preIncDecExpr</c>
	/// labeled alternative in <see cref="LSLParser.typeCastExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPreIncDecExpr([NotNull] LSLParser.PreIncDecExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>preIncDecExpr</c>
	/// labeled alternative in <see cref="LSLParser.typeCastExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPreIncDecExpr([NotNull] LSLParser.PreIncDecExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>preIncrement</c>
	/// labeled alternative in <see cref="LSLParser.preIncDecExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPreIncrement([NotNull] LSLParser.PreIncrementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>preIncrement</c>
	/// labeled alternative in <see cref="LSLParser.preIncDecExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPreIncrement([NotNull] LSLParser.PreIncrementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>preDecrement</c>
	/// labeled alternative in <see cref="LSLParser.preIncDecExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPreDecrement([NotNull] LSLParser.PreDecrementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>preDecrement</c>
	/// labeled alternative in <see cref="LSLParser.preIncDecExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPreDecrement([NotNull] LSLParser.PreDecrementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>postfixExpr</c>
	/// labeled alternative in <see cref="LSLParser.preIncDecExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPostfixExpr([NotNull] LSLParser.PostfixExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>postfixExpr</c>
	/// labeled alternative in <see cref="LSLParser.preIncDecExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPostfixExpr([NotNull] LSLParser.PostfixExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>subscriptPostfix</c>
	/// labeled alternative in <see cref="LSLParser.postfixExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubscriptPostfix([NotNull] LSLParser.SubscriptPostfixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>subscriptPostfix</c>
	/// labeled alternative in <see cref="LSLParser.postfixExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubscriptPostfix([NotNull] LSLParser.SubscriptPostfixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>postIncrementPostfix</c>
	/// labeled alternative in <see cref="LSLParser.postfixExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPostIncrementPostfix([NotNull] LSLParser.PostIncrementPostfixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>postIncrementPostfix</c>
	/// labeled alternative in <see cref="LSLParser.postfixExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPostIncrementPostfix([NotNull] LSLParser.PostIncrementPostfixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>primaryExpr</c>
	/// labeled alternative in <see cref="LSLParser.postfixExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimaryExpr([NotNull] LSLParser.PrimaryExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>primaryExpr</c>
	/// labeled alternative in <see cref="LSLParser.postfixExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimaryExpr([NotNull] LSLParser.PrimaryExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>postDecrementPostfix</c>
	/// labeled alternative in <see cref="LSLParser.postfixExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPostDecrementPostfix([NotNull] LSLParser.PostDecrementPostfixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>postDecrementPostfix</c>
	/// labeled alternative in <see cref="LSLParser.postfixExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPostDecrementPostfix([NotNull] LSLParser.PostDecrementPostfixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>methodCallPostfix</c>
	/// labeled alternative in <see cref="LSLParser.postfixExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodCallPostfix([NotNull] LSLParser.MethodCallPostfixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>methodCallPostfix</c>
	/// labeled alternative in <see cref="LSLParser.postfixExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodCallPostfix([NotNull] LSLParser.MethodCallPostfixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>stringLiteral</c>
	/// labeled alternative in <see cref="LSLParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringLiteral([NotNull] LSLParser.StringLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>stringLiteral</c>
	/// labeled alternative in <see cref="LSLParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringLiteral([NotNull] LSLParser.StringLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>integerLiteral</c>
	/// labeled alternative in <see cref="LSLParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntegerLiteral([NotNull] LSLParser.IntegerLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>integerLiteral</c>
	/// labeled alternative in <see cref="LSLParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntegerLiteral([NotNull] LSLParser.IntegerLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>floatLiteral</c>
	/// labeled alternative in <see cref="LSLParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFloatLiteral([NotNull] LSLParser.FloatLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>floatLiteral</c>
	/// labeled alternative in <see cref="LSLParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFloatLiteral([NotNull] LSLParser.FloatLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>vectorLiteralExpr</c>
	/// labeled alternative in <see cref="LSLParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVectorLiteralExpr([NotNull] LSLParser.VectorLiteralExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>vectorLiteralExpr</c>
	/// labeled alternative in <see cref="LSLParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVectorLiteralExpr([NotNull] LSLParser.VectorLiteralExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>listLiteralExpr</c>
	/// labeled alternative in <see cref="LSLParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterListLiteralExpr([NotNull] LSLParser.ListLiteralExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>listLiteralExpr</c>
	/// labeled alternative in <see cref="LSLParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitListLiteralExpr([NotNull] LSLParser.ListLiteralExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>rotationLiteralExpr</c>
	/// labeled alternative in <see cref="LSLParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRotationLiteralExpr([NotNull] LSLParser.RotationLiteralExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>rotationLiteralExpr</c>
	/// labeled alternative in <see cref="LSLParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRotationLiteralExpr([NotNull] LSLParser.RotationLiteralExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>idExpr</c>
	/// labeled alternative in <see cref="LSLParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdExpr([NotNull] LSLParser.IdExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>idExpr</c>
	/// labeled alternative in <see cref="LSLParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdExpr([NotNull] LSLParser.IdExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>parenExpr</c>
	/// labeled alternative in <see cref="LSLParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParenExpr([NotNull] LSLParser.ParenExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>parenExpr</c>
	/// labeled alternative in <see cref="LSLParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParenExpr([NotNull] LSLParser.ParenExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LSLParser.vecLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVecLiteral([NotNull] LSLParser.VecLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LSLParser.vecLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVecLiteral([NotNull] LSLParser.VecLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LSLParser.rotLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRotLiteral([NotNull] LSLParser.RotLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LSLParser.rotLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRotLiteral([NotNull] LSLParser.RotLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LSLParser.listLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterListLiteral([NotNull] LSLParser.ListLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LSLParser.listLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitListLiteral([NotNull] LSLParser.ListLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LSLParser.listContents"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterListContents([NotNull] LSLParser.ListContentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LSLParser.listContents"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitListContents([NotNull] LSLParser.ListContentsContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
