[OSSL]
  AllowOSFunctions = true
  AllowMODFunctions = true
  AllowLightShareFunctions = true
  PermissionErrorToOwner = false

  OSFunctionThreatLevel = VeryLow

  osslParcelO = "PARCEL_OWNER,"
  osslParcelOG = "PARCEL_GROUP_MEMBER,PARCEL_OWNER,"
  osslNPC = ${OSSL|osslParcelOG}ESTATE_MANAGER,ESTATE_OWNER
  
  ; ThreatLevel  None
  Allow_osGetAgents =               true
  Allow_osGetAvatarList =           true
  Allow_osGetGender =               true
  Allow_osGetHealth =               true
  ; Allow_osGetHealRate =             true
  Allow_osGetNPCList =              ${OSSL|osslParcelOG}ESTATE_MANAGER,ESTATE_OWNER
  Allow_osGetRezzingObject =        true
  Allow_osGetSunParam =             true
  Allow_osNpcGetOwner =             ${OSSL|osslNPC}
  Allow_osSetSunParam =             ${OSSL|osslParcelOG}ESTATE_MANAGER,ESTATE_OWNER
  Allow_osTeleportOwner =           true
  Allow_osWindActiveModelPluginName = true

  ; ThreatLevel  Nuisance
  Allow_osSetEstateSunSettings =    ESTATE_MANAGER,ESTATE_OWNER
  Allow_osSetRegionSunSettings =    ESTATE_MANAGER,ESTATE_OWNER

  ; ThreatLevel  VeryLow
  Allow_osEjectFromGroup =          true
  Allow_osForceBreakAllLinks =      ${OSSL|osslParcelOG}ESTATE_MANAGER,ESTATE_OWNER
  Allow_osForceBreakLink =          ${OSSL|osslParcelOG}ESTATE_MANAGER,ESTATE_OWNER
  Allow_osGetWindParam =            true
  Allow_osInviteToGroup =           true
  Allow_osReplaceString =           true
  Allow_osSetDynamicTextureData =   true
  Allow_osSetDynamicTextureDataFace = true
  Allow_osSetDynamicTextureDataBlend = true
  Allow_osSetDynamicTextureDataBlendFace = true
  Allow_osSetDynamicTextureURL =    true
  Allow_osSetParcelMediaURL =       ${OSSL|osslParcelOG}ESTATE_MANAGER,ESTATE_OWNER
  Allow_osSetParcelMusicURL =       ${OSSL|osslParcelOG}ESTATE_MANAGER,ESTATE_OWNER
  Allow_osSetParcelSIPAddress =     ${OSSL|osslParcelOG}ESTATE_MANAGER,ESTATE_OWNER
  Allow_osSetPrimFloatOnWater =     true
  Allow_osSetWindParam =            ${OSSL|osslParcelOG}ESTATE_MANAGER,ESTATE_OWNER
  Allow_osTerrainFlush =            ESTATE_MANAGER,ESTATE_OWNER
  Allow_osUnixTimeToTimestamp =     true

  ; ThreatLevel  Low
  Allow_osAvatarName2Key =          true
  Allow_osFormatString =            true
  Allow_osKey2Name =                true
  Allow_osListenRegex =             true
  Allow_osLoadedCreationDate =      ${OSSL|osslParcelOG}ESTATE_MANAGER,ESTATE_OWNER
  Allow_osLoadedCreationID =        ${OSSL|osslParcelOG}ESTATE_MANAGER,ESTATE_OWNER
  Allow_osLoadedCreationTime =      ${OSSL|osslParcelOG}ESTATE_MANAGER,ESTATE_OWNER
  Allow_osMessageObject =           true
  Allow_osRegexIsMatch =            true
  Allow_osGetAvatarHomeURI =        ${OSSL|osslParcelOG}ESTATE_MANAGER,ESTATE_OWNER
  Allow_osNpcSetProfileAbout =      ${OSSL|osslNPC}
  Allow_osNpcSetProfileImage =      ${OSSL|osslNPC}
  Allow_osDie =                     ${OSSL|osslParcelOG}ESTATE_MANAGER,ESTATE_OWNER

  ; ThreatLevel  Moderate
  Allow_osDetectedCountry =         ${OSSL|osslParcelO}ESTATE_MANAGER,ESTATE_OWNER
  Allow_osDropAttachment =          true
  Allow_osDropAttachmentAt =        ${OSSL|osslParcelO}ESTATE_MANAGER,ESTATE_OWNER
  Allow_osGetAgentCountry =         ${OSSL|osslParcelO}ESTATE_MANAGER,ESTATE_OWNER
  Allow_osGetGridCustom =           true
  Allow_osGetGridGatekeeperURI =    true
  Allow_osGetGridHomeURI =          true
  Allow_osGetGridLoginURI =         true
  Allow_osGetGridName =             true
  Allow_osGetGridNick =             true
  Allow_osGetNumberOfAttachments =  ${OSSL|osslParcelO}ESTATE_MANAGER,ESTATE_OWNER
  Allow_osGetRegionStats =          ${OSSL|osslParcelO}ESTATE_MANAGER,ESTATE_OWNER
  Allow_osGetSimulatorMemory =      true
  Allow_osGetSimulatorMemoryKB =    true
  Allow_osMessageAttachments =      ${OSSL|osslParcelO}ESTATE_MANAGER,ESTATE_OWNER
  Allow_osReplaceAgentEnvironment = ${OSSL|osslParcelO}ESTATE_MANAGER,ESTATE_OWNER
  Allow_osSetSpeed =                true
  Allow_osSetOwnerSpeed =           ${OSSL|osslParcelO}ESTATE_MANAGER,ESTATE_OWNER
  Allow_osRequestURL =              ${OSSL|osslParcelO}ESTATE_MANAGER,ESTATE_OWNER
  Allow_osRequestSecureURL =        ${OSSL|osslParcelO}ESTATE_MANAGER,ESTATE_OWNER

  ; ThreatLevel High
  Allow_osCauseDamage =             true
  Allow_osCauseHealing =            true
  Allow_osSetHealth =               ${OSSL|osslParcelO}ESTATE_MANAGER,ESTATE_OWNER
  Allow_osSetHealRate =             ${OSSL|osslParcelO}ESTATE_MANAGER,ESTATE_OWNER
  Allow_osForceAttachToAvatar =     ${OSSL|osslParcelO}ESTATE_MANAGER,ESTATE_OWNER
  Allow_osForceAttachToAvatarFromInventory = ${OSSL|osslParcelO}ESTATE_MANAGER,ESTATE_OWNER
  Allow_osForceCreateLink =         ${OSSL|osslParcelO}ESTATE_MANAGER,ESTATE_OWNER
  Allow_osForceDropAttachment =     true
  Allow_osForceDropAttachmentAt =   true
  Allow_osGetLinkPrimitiveParams =  ${OSSL|osslParcelO}ESTATE_MANAGER,ESTATE_OWNER
  Allow_osGetPhysicsEngineType =    true
  Allow_osGetRegionMapTexture =     ${OSSL|osslParcelO}ESTATE_MANAGER,ESTATE_OWNER
  Allow_osGetScriptEngineName =     true
  Allow_osGetSimulatorVersion =     true
  Allow_osMakeNotecard =            true
  Allow_osMatchString =             true
  Allow_osNpcCreate =               true
  Allow_osNpcCreateNew =            true
  Allow_osNpcGetPos =               true
  Allow_osNpcGetRot =               true
  Allow_osNpcLoadAppearance =       true
  Allow_osNpcMoveTo =               true
  Allow_osNpcMoveToTarget =         true
  Allow_osNpcPlayAnimation =        true
  Allow_osNpcRemove =               true
  Allow_osNpcSaveAppearance =       true
  Allow_osNpcSay =                  true
  Allow_osNpcSayTo =                ${OSSL|osslNPC}
  Allow_osNpcSetRot =               true
  Allow_osNpcShout =                true
  Allow_osNpcSit =                  true
  Allow_osNpcStand =                true
  Allow_osNpcStopAnimation =        true
  Allow_osNpcStopMoveToTarget =     true
  Allow_osNpcTouch =                true
  Allow_osNpcWhisper =              true
  Allow_osOwnerSaveAppearance =     true
  Allow_osParcelJoin =              ESTATE_MANAGER,ESTATE_OWNER
  Allow_osParcelSubdivide =         ESTATE_MANAGER,ESTATE_OWNER
  Allow_osRegionRestart =           ESTATE_MANAGER,ESTATE_OWNER
  Allow_osRegionNotice =            ESTATE_MANAGER,ESTATE_OWNER
  Allow_osSetProjectionParams =     ${OSSL|osslParcelOG}ESTATE_MANAGER,ESTATE_OWNER
  Allow_osSetRegionWaterHeight =    ESTATE_MANAGER,ESTATE_OWNER
  Allow_osSetTerrainHeight =        ESTATE_MANAGER,ESTATE_OWNER
  Allow_osSetTerrainTexture =       ESTATE_MANAGER,ESTATE_OWNER
  Allow_osSetTerrainTextureHeight = ESTATE_MANAGER,ESTATE_OWNER
  Allow_osNgcPlaySoundURL = true
  ; ThreatLevel  VeryHigh
  Allow_osAgentSaveAppearance =     ESTATE_MANAGER,ESTATE_OWNER,GRID_GOD
  ; Warning: The next function allows scripts to force animations on avatars without the user giving permission.
  ;   Enabling this can allow forced animations which can trigger traumatic episodes in vulnerable populations.
  ;   Similar things can be said for several of the 'force' functions. Enable with care and control.
  ; Some of these were added as early functionality for NPCs. This has been replaced with the NPC functions.
  Allow_osAvatarPlayAnimation =     ESTATE_MANAGER,ESTATE_OWNER
  Allow_osAvatarStopAnimation =     ESTATE_MANAGER,ESTATE_OWNER
  Allow_osForceAttachToOtherAvatarFromInventory = ESTATE_MANAGER,ESTATE_OWNER
  Allow_osForceDetachFromAvatar =   true
  Allow_osForceOtherSit =           ${OSSL|osslParcelOG}ESTATE_MANAGER,ESTATE_OWNER

  ; The notecard functions can cause a lot of load on the region if over used
  Allow_osGetNotecard =             true
  Allow_osGetNotecardLine =         true
  Allow_osGetNumberOfNotecardLines = true
  Allow_osSetDynamicTextureURL =    true
  Allow_osSetDynamicTextureURLBlend = true
  Allow_osSetDynamicTextureURLBlendFace = true
  Allow_osSetRot  =                 ESTATE_MANAGER,ESTATE_OWNER
  Allow_osSetParcelDetails =        ${OSSL|osslParcelO}ESTATE_MANAGER,ESTATE_OWNER

  ; ThreatLevel  Severe
  Allow_osConsoleCommand =          ESTATE_OWNER,GRID_GOD
  Allow_osKickAvatar =              ${OSSL|osslParcelO}ESTATE_MANAGER,ESTATE_OWNER
  Allow_osTeleportAgent =           true
  Allow_osTeleportObject =          ${OSSL|osslParcelO}ESTATE_MANAGER,ESTATE_OWNER

  ; ThreatLevel  Severe with additional internal restrictions
  Allow_osGetAgentIP =              true   ; always restricted to Administrators (true or false to disable)
  Allow_osSetContentType =          false
