<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>TasiaAddons.Abstractions</AssemblyName>
    <RootNamespace>TasiaAddons.Abstractions</RootNamespace>
    <Company>Tasia Extensions</Company>
    <Product>Tasia Addons - Abstractions</Product>
    <Version>1.0.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Nini">
      <HintPath>$(SolutionDir)/bin/Nini.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenMetaverseTypes">
      <HintPath>$(SolutionDir)/bin/OpenMetaverseTypes.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
</Project>
