[enable]
opensim = true
robust = true

[programs]
robust = dotnet Robust.dll
opensim = dotnet OpenSim.Server.MoneyServer.dll
;opensim = dotnet OpenSim.dll -inifile ./Regions/grid-welcome/Opensim.ini
[settings]
use_pid_file = false

[session_names]
robust = robust_session
opensim = opensim_session