[Groups]
Enabled = true
Module = "Groups Module V2"
NoticesEnabled = true
MessagingModule = "Groups Messaging Module V2"
MessagingEnabled = true
;Must be true for Groups Messaging Module V2:
MessageOnlineUsersOnly = true
;hg only:
ServicesConnectorModule = "Groups HG Service Connector"
GroupsServerURI = "${Const|BaseURL}:${Const|PrivatePort}"
GroupsExternalURI="${Const|BaseURL}:${Const|PublicPort}"
LocalService = remote
HomeURI = "${Const|BaseURL}:${Const|PublicPort}"

;[Groups]
;    Enabled = true
;    Module = "Groups Module V2"
;    GroupsServerURI = ${Const|PrivURL}:${Const|PrivatePort}
;    MessagingModule = "Groups Messaging Module V2"
;    ServicesConnectorModule = "Groups HG Service Connector";
	;HomeURI="${Const|BaseURL}:${Const|PublicPort}"
    ;LocalService = remote
    ;HomeURI = "http://CHANGE_ME_HOST:8002"
    ;GroupsServerURI = "${Const|BaseURL}:${Const|PrivatePort}"
	;GroupsExternalURI="${Const|BaseURL}:${Const|PublicPort}"
    ;MessagingEnabled = true
    ;NoticesEnabled = true
	; LevelGroupCreate = 0
    ; SecretKey = ""
    ; MessageOnlineUsersOnly = false
    ;StorageProvider = OpenSim.Data.MySQL.dll
	;DebugEnabled = true
    ;DebugMessagingEnabled = true
    ;XmlRpcServiceReadKey    = 5432
    ;XmlRpcServiceWriteKey   = 5432
    
;[Groups]
;    Enabled = true
;    Module = GroupsModule
;    MessagingEnabled = true
;    MessagingModule = GroupsMessagingModule
;    ServicesConnectorModule = XmlRpcGroupsServicesConnector
;    GroupsServerURI = "http://nossl.CHANGE_ME_HOST/group/martyrpc.php"
;    NoticesEnabled = true
   ;DebugEnabled = false
    ;XmlRpcServiceReadKey    = 5655
    ;XmlRpcServiceWriteKey   = 5656
	;NoVerifyCertChain = true
    ;NoVerifyCertHostname = true
	

