[Messaging]
    ; OfflineMessageModule = OfflineMessageModule
    OfflineMessageModule = "Offline Message Module V2"
    OfflineMessageURL = http://CHANGE_ME_HOST:8003
	; OfflineMessageURL = https://CHANGE_ME_HOST/ostools/offline.php
    ; StorageProvider = OpenSim.Data.MySQL.dll
    MuteListModule = MuteListModule
    ; ForwardOfflineGroupMessages = true
