[Network]
    ConsoleUser = "Console User"
    ConsolePass = "CHANGE_ME_CONSOLE_PASS"
    console_port = ${Const|http_listener_port}
    http_listener_port = ${Const|http_listener_port}
    ;http_listener_ssl = false
    ;http_listener_sslport = 9001
    ;http_listener_cn = "myRegionsExternalHostName"
    ;http_listener_cert_path = "SSL\ssl\OpenSim.p12"
    ;http_listener_cert_pass = "mycertpass"
    ; OutboundDisallowForUserScriptsExcept = 192.168.1.0/24
    HttpBodyMaxLenMAX=1638400
    ExternalHostNameForLSL = ${Const|BaseHostname}
    shard = "OpenSim"
    user_agent = "I-Grid LSL (Mozilla Compatible)"
    ; HttpAuthUsername = "some_username"
    ; HttpAuthPassword = "some_password"
    
