[InterestManagement]
    ; UpdatePrioritizationScheme = BestAvatarResponsiveness
    ; ObjectsCullingByDistance = false
[MediaOnAPrim]
    ; Enabled = true
[NPC]
     Enabled = true
     MaxNumberNPCsPerScene = 120
     AllowNotOwned = true
     AllowSenseAsAvatar = true
     AllowCloneOtherAvatars = true
     NoNPCGroup = true
     AutoAnimationByDefault = false
     AskPermissionByDefault = false
[Terrain]
    ; InitialTerrain = "pinhead-island"
[LandManagement]
    ;ShowParcelBansLines = true
[UserProfiles]
   ProfileServiceURL = ${Const|BaseURL}:${Const|PublicPort}
   AllowUserProfileWebURLs = true

[XBakes]
   URL = ${Const|PrivURL}:${Const|PrivatePort}
[GodNames]
     Enabled = true
     FullNames = "Testing User, Super User,User Name"
     Surnames = "Mole"
[Experience]
    ;# {Enabled} {} {Use Experience Tools on this region} {true false} false
     Enabled = true

