[Search]
SearchURL = 
"http://CHANGE_ME_HOST/api4opensim/query.php?gk=http://CHANGE_ME_HOST:8002"

[SimulatorFeatures]
    ;SearchServerURI = "http://127.0.0.1:9000/
    DestinationGuideURI = "https://CHANGE_ME_HOST/api4opensim/guide"