<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>TasiaAddons.WoWonder</AssemblyName>
    <RootNamespace>TasiaAddons.WoWonder</RootNamespace>
    <Company>Tasia Extensions</Company>
    <Product>Tasia Addons - WoWonder</Product>
    <Version>1.0.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="log4net">
      <HintPath>$(SolutionDir)/bin/log4net.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Nini">
      <HintPath>$(SolutionDir)/bin/Nini.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenMetaverse">
      <HintPath>$(SolutionDir)/bin/OpenMetaverse.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenMetaverseTypes">
      <HintPath>$(SolutionDir)/bin/OpenMetaverseTypes.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenMetaverse.StructuredData">
      <HintPath>$(SolutionDir)/bin/OpenMetaverse.StructuredData.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenSim.Framework">
      <HintPath>$(SolutionDir)/bin/OpenSim.Framework.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenSim.Framework.Servers">
      <HintPath>$(SolutionDir)/bin/OpenSim.Framework.Servers.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenSim.Framework.Servers.HttpServer">
      <HintPath>$(SolutionDir)/bin/OpenSim.Framework.Servers.HttpServer.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenSim.Server.Base">
      <HintPath>$(SolutionDir)/bin/OpenSim.Server.Base.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenSim.Server.Handlers">
      <HintPath>$(SolutionDir)/bin/OpenSim.Server.Handlers.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenSim.Services.Interfaces">
      <HintPath>$(SolutionDir)/bin/OpenSim.Services.Interfaces.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="XMLRPC">
      <HintPath>$(SolutionDir)/bin/XMLRPC.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="$(SolutionDir)/addon-modules/TasiaAddons.Abstractions/TasiaAddons.Abstractions.csproj" />
  </ItemGroup>
</Project>
