<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyTitle>OpenSim.Addons.Groups</AssemblyTitle>
    <Company>http://opensimulator.org</Company>
    <Product>OpenSim.Addons.Groups</Product>
    <Copyright>Copyright (c) OpenSimulator.org Developers</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="NDesk.Options" HintPath="..\..\Library\NDesk.Options.dll" />
    <Reference Include="xmlrpc" HintPath="..\..\Library\xmlrpc.dll" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Source\OpenSim.Data\OpenSim.Data.csproj" Private="false" />
    <ProjectReference Include="..\..\Source\OpenSim.Framework\OpenSim.Framework.csproj" Private="false" />
    <ProjectReference Include="..\..\Source\OpenSim.Framework.Monitoring\OpenSim.Framework.Monitoring.csproj" Private="false" />
    <ProjectReference Include="..\..\Source\OpenSim.Framework.Servers\OpenSim.Framework.Servers.csproj" Private="false" />
    <ProjectReference Include="..\..\Source\OpenSim.Framework.Servers.HttpServer\OpenSim.Framework.Servers.HttpServer.csproj" Private="false" />
    <ProjectReference Include="..\..\Source\OpenSim.Region.Framework\OpenSim.Region.Framework.csproj" Private="false" />
    <ProjectReference Include="..\..\Source\OpenSim.Server.Base\OpenSim.Server.Base.csproj" Private="false" />
    <ProjectReference Include="..\..\Source\OpenSim.Server.Handlers\OpenSim.Server.Handlers.csproj" Private="false" />
    <ProjectReference Include="..\..\Source\OpenSim.Services.Base\OpenSim.Services.Base.csproj" Private="false" />
    <ProjectReference Include="..\..\Source\OpenSim.Services.Interfaces\OpenSim.Services.Interfaces.csproj" Private="false" />
  </ItemGroup>

</Project>
