  <Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyTitle>Gloebit</AssemblyTitle>
    <Product>Gloebit</Product>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="xmlrpc" HintPath="..\..\Library\xmlrpc.dll" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Source\OpenSim.Data\OpenSim.Data.csproj" Private="false" />
    <ProjectReference Include="..\..\Source\OpenSim.Data.MySQL\OpenSim.Data.MySQL.csproj" Private="false" />
    <ProjectReference Include="..\..\Source\OpenSim.Data.PGSQL\OpenSim.Data.PGSQL.csproj" Private="false" />
    <ProjectReference Include="..\..\Source\OpenSim.Data.SQLite\OpenSim.Data.SQLite.csproj" Private="false" />
    <ProjectReference Include="..\..\Source\OpenSim.Framework\OpenSim.Framework.csproj" Private="false" />
    <ProjectReference Include="..\..\Source\OpenSim.Framework.Servers\OpenSim.Framework.Servers.csproj" Private="false" />
    <ProjectReference Include="..\..\Source\OpenSim.Framework.Servers.HttpServer\OpenSim.Framework.Servers.HttpServer.csproj" Private="false" />
    <ProjectReference Include="..\..\Source\OpenSim.Region.CoreModules\OpenSim.Region.CoreModules.csproj" Private="false" />
    <ProjectReference Include="..\..\Source\OpenSim.Region.Framework\OpenSim.Region.Framework.csproj" Private="false" />
    <ProjectReference Include="..\..\Source\OpenSim.Region.OptionalModules\OpenSim.Region.OptionalModules.csproj" Private="false" />
    <ProjectReference Include="..\..\Source\OpenSim.Server.Base\OpenSim.Server.Base.csproj" Private="false" />
    <ProjectReference Include="..\..\Source\OpenSim.Services.Interfaces\OpenSim.Services.Interfaces.csproj" Private="false" />
    <ProjectReference Include="..\..\Source\OpenSim.Region.ScriptEngine.Shared\OpenSim.Region.ScriptEngine.Shared.csproj" Private="false" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\GloebitSubscriptionsMySQL.migrations" />
    <EmbeddedResource Include="Resources\GloebitSubscriptionsPGSQL.migrations" />
    <EmbeddedResource Include="Resources\GloebitSubscriptionsSQLite.migrations" />
    <EmbeddedResource Include="Resources\GloebitTransactionsMySQL.migrations" />
    <EmbeddedResource Include="Resources\GloebitTransactionsPGSQL.migrations" />
    <EmbeddedResource Include="Resources\GloebitTransactionsSQLite.migrations" />
    <EmbeddedResource Include="Resources\GloebitUsersMySQL.migrations" />
    <EmbeddedResource Include="Resources\GloebitUsersPGSQL.migrations" />
    <EmbeddedResource Include="Resources\GloebitUsersSQLite.migrations" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="MySqlConnector" Version="2.6.1" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.10" />
  </ItemGroup>

</Project>
