<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Tasia.Extensions.Loader</AssemblyName>
    <RootNamespace>Tasia.Extensions.Loader</RootNamespace>
    <Company>Tasia Extensions</Company>
    <Product>Tasia Extensions Loader</Product>
    <Version>1.0.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="log4net">
      <HintPath>..\..\bin\log4net.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Nini">
      <HintPath>..\..\bin\Nini.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Tasia.Extensions.SDK\Tasia.Extensions.SDK.csproj" />
  </ItemGroup>
</Project>
