
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using OpenMetaverse;

using InWorldz.Phlox.Types;

namespace InWorldz.Phlox.Glue
{
	public interface ISystemAPI
	{
        void SetScriptEventFlags();

        /// <summary>
        /// Signal that a long-running syscall has finished, so the scheduler can take the
        /// script out of <c>Status.Syscall</c>. An implementation that already posts its own return
        /// may call this too - a return that arrives when the script is no longer in Syscall is
        /// ignored (<c>PhloxExecutionScheduler.ProcessSyscallReturns:897</c>).
        /// </summary>
        void CompleteSyscall();
        void ShoutError(string errorText);
        void OnScriptReset();
        void OnStateChange();
        void OnScriptUnloaded(ScriptUnloadReason reason, VM.RuntimeState.LocalDisableFlag localFlag);
        void AddExecutionTime(double ms);
        void OnScriptInjected(bool fromCrossing);
        void OnGroupCrossedAvatarReady(UUID avatarId);
        float GetAverageScriptTime();

		float llSin(float theta);
		float llCos(float theta);
		float llTan(float theta);
		float llAtan2(float y,float x);
		float llSqrt(float val);
		float llPow(float decbase,float exponent);
		int llAbs(int val);
		float llFabs(float val);
		float llFrand(float mag);
		int llFloor(float val);
		int llCeil(float val);
		int llRound(float val);
		float llVecMag(Vector3 v);
		Vector3 llVecNorm(Vector3 v);
		float llVecDist(Vector3 v1,Vector3 v2);
		Vector3 llRot2Euler(Quaternion q);
		Quaternion llEuler2Rot(Vector3 v);
		Quaternion llAxes2Rot(Vector3 fwd,Vector3 left,Vector3 up);
		Vector3 llRot2Fwd(Quaternion q);
		Vector3 llRot2Left(Quaternion q);
		Vector3 llRot2Up(Quaternion q);
		Quaternion llRotBetween(Vector3 v1,Vector3 v2);
		void llWhisper(int channel,string msg);
		void llSay(int channel,string msg);
		void llShout(int channel,string msg);
		int llListen(int channel,string name,string id,string msg);
		void llListenControl(int number,int active);
		void llListenRemove(int number);
		void llSensor(string name,string id,int type,float range,float arc);
		void llSensorRepeat(string name,string id,int type,float range,float arc,float rate);
		void llSensorRemove();
		string llDetectedName(int number);
		string llDetectedKey(int number);
		string llDetectedOwner(int number);
		int llDetectedType(int number);
		Vector3 llDetectedPos(int number);
		Vector3 llDetectedVel(int number);
		Vector3 llDetectedGrab(int number);
		Quaternion llDetectedRot(int number);
		int llDetectedGroup(int number);
		int llDetectedLinkNumber(int number);
		void llDie();
		float llGround(Vector3 offset);
		float llCloud(Vector3 offset);
		Vector3 llWind(Vector3 offset);
		void llSetStatus(int status,int value);
		int llGetStatus(int status);
		void llSetScale(Vector3 scale);
		Vector3 llGetScale();
		void llSetColor(Vector3 color,int face);
		float llGetAlpha(int face);
		void llSetAlpha(float alpha,int face);
		Vector3 llGetColor(int face);
		void llSetTexture(string texture,int face);
		void llScaleTexture(float u,float v,int face);
		void llOffsetTexture(float u,float v,int face);
		void llRotateTexture(float rot,int face);
		string llGetTexture(int face);
		void llSetPos(Vector3 pos);
		Vector3 llGetPos();
		Vector3 llGetLocalPos();
		void llSetRot(Quaternion rot);
		Quaternion llGetRot();
		Quaternion llGetLocalRot();
		void llSetForce(Vector3 force,int local);
		Vector3 llGetForce();
		int llTarget(Vector3 position,float range);
		void llTargetRemove(int number);
		int llRotTarget(Quaternion rot,float error);
		void llRotTargetRemove(int number);
		void llMoveToTarget(Vector3 target,float tau);
		void llStopMoveToTarget();
		void llApplyImpulse(Vector3 force,int local);
		void llApplyRotationalImpulse(Vector3 force,int local);
		void llSetTorque(Vector3 torque,int local);
		Vector3 llGetTorque();
		void llSetForceAndTorque(Vector3 force,Vector3 torque,int local);
		Vector3 llGetVel();
        Vector3 iwGetAngularVelocity();
		Vector3 llGetAccel();
		Vector3 llGetOmega();
		float llGetTimeOfDay();
		float llGetWallclock();
		float llGetTime();
		void llResetTime();
		float llGetAndResetTime();
		void llSound(string sound,float volume,int queue,int loop);
		void llPlaySound(string sound,float volume);
		void llLoopSound(string sound,float volume);
		void llLoopSoundMaster(string sound,float volume);
		void llLoopSoundSlave(string sound,float volume);
		void llPlaySoundSlave(string sound,float volume);
		void llTriggerSound(string sound,float volume);
		void llStopSound();
		void llPreloadSound(string sound);
		string llGetSubString(string src,int start,int end);
		string llDeleteSubString(string src,int start,int end);
		string llInsertString(string dst,int position,string src);
		string llToUpper(string src);
		string llToLower(string src);
		int llGiveMoney(string destination,int amount);
		void llMakeExplosion(int particles,float scale,float vel,float lifetime,float arc,string texture,Vector3 offset);
		void llMakeFountain(int particles,float scale,float vel,float lifetime,float arc,int bounce,string texture,Vector3 offset,float bounce_offset);
		void llMakeSmoke(int particles,float scale,float vel,float lifetime,float arc,string texture,Vector3 offset);
		void llMakeFire(int particles,float scale,float vel,float lifetime,float arc,string texture,Vector3 offset);
		void llRezObject(string inventory,Vector3 pos,Vector3 vel,Quaternion rot,int param);
		void llLookAt(Vector3 target,float strength,float damping);
		void llStopLookAt();
		void llSetTimerEvent(float sec);
		void llSleep(float sec);
		float llGetMass();
		void llCollisionFilter(string name,string id,int accept);
		void llTakeControls(int controls,int accept,int pass_on);
		void llReleaseControls();
		void llAttachToAvatar(int attach_point);
		void llDetachFromAvatar();
		void llTakeCamera(string avatar);
		void llReleaseCamera(string avatar);
		string llGetOwner();
		void llInstantMessage(string user,string message);
		void llEmail(string address,string subject,string message);
		void llGetNextEmail(string address,string subject);
		string llGetKey();
		void llSetBuoyancy(float buoyancy);
		void llSetHoverHeight(float height,int water,float tau);
		void llStopHover();
		void llMinEventDelay(float delay);
		void llSoundPreload(string sound);
		void llRotLookAt(Quaternion target,float strength,float damping);
		int llStringLength(string str);
		void llStartAnimation(string anim);
		void llStopAnimation(string anim);
		void llPointAt(Vector3 pos);
		void llStopPointAt();
		void llTargetOmega(Vector3 axis,float spinrate,float gain);
		int llGetStartParameter();
		void llGodLikeRezObject(string inventory,Vector3 pos);
		void llRequestPermissions(string agent,int perm);
		string llGetPermissionsKey();
		int llGetPermissions();
		int llGetLinkNumber();
		void llSetLinkColor(int linknumber,Vector3 color,int face);
		void llCreateLink(string target,int parent);
		void llBreakLink(int linknum);
		void llBreakAllLinks();
		string llGetLinkKey(int linknumber);
		string llGetLinkName(int linknumber);
		int llGetInventoryNumber(int type);
		string llGetInventoryName(int type,int number);
		void llSetScriptState(string name,int run);
		float llGetEnergy();
		void llGiveInventory(string destination,string inventory);
		void llRemoveInventory(string item);
		void llSetText(string text,Vector3 color,float alpha);
		float llWater(Vector3 offset);
		void llPassTouches(int pass);
		void llRequestAgentData(string id,int data);
        string llRequestInventoryData(string name);
		void llSetDamage(float damage);
		void llTeleportAgentHome(string id);
		void llModifyLand(int action,int brush);
		void llCollisionSound(string impact_sound,float impact_volume);
		void llCollisionSprite(string impact_sprite);
		string llGetAnimation(string id);
		void llResetScript();
		void llMessageLinked(int linknum,int num,string str,string id);
		void llPushObject(string id,Vector3 impulse,Vector3 ang_impulse,int local);
		void llPassCollisions(int pass);
		string llGetScriptName();
		int llGetNumberOfSides();
		Quaternion llAxisAngle2Rot(Vector3 axis,float angle);
		Vector3 llRot2Axis(Quaternion rot);
		float llRot2Angle(Quaternion rot);
		float llAcos(float val);
		float llAsin(float val);
		float llAngleBetween(Quaternion a,Quaternion b);
		string llGetInventoryKey(string name);
		void llAllowInventoryDrop(int add);
		Vector3 llGetSunDirection();
		Vector3 llGetTextureOffset(int face);
		Vector3 llGetTextureScale(int side);
		float llGetTextureRot(int side);
		int llSubStringIndex(string source,string pattern);
        string llGetOwnerKey(string id);
		Vector3 llGetCenterOfMass();
		LSLList llListSort(LSLList src,int stride,int ascending);
		int llGetListLength(LSLList src);
		int llList2Integer(LSLList src,int index);
		float llList2Float(LSLList src,int index);
		string llList2String(LSLList src,int index);
		string llList2Key(LSLList src,int index);
		Vector3 llList2Vector(LSLList src,int index);
		Quaternion llList2Rot(LSLList src,int index);
		LSLList llList2List(LSLList src,int start,int end);
		LSLList llDeleteSubList(LSLList src,int start,int end);
		int llGetListEntryType(LSLList src,int index);
		string llList2CSV(LSLList src);
		LSLList llCSV2List(string src);
		LSLList llListRandomize(LSLList src,int stride);
		LSLList llList2ListStrided(LSLList src,int start,int end,int stride);
		Vector3 llGetRegionCorner();
		LSLList llListInsertList(LSLList dest,LSLList src,int start);
		int llListFindList(LSLList src,LSLList test);
		string llGetObjectName();
		void llSetObjectName(string name);
		string llGetDate();
		int llEdgeOfWorld(Vector3 pos,Vector3 dir);
		int llGetAgentInfo(string id);
		void llAdjustSoundVolume(float volume);
		void llSetSoundQueueing(int queue);
		void llSetSoundRadius(float radius);
		string llKey2Name(string id);
		void llSetTextureAnim(int mode,int face,int sizex,int sizey,float start,float length,float rate);
		void llTriggerSoundLimited(string sound,float volume,Vector3 top_north_east,Vector3 bottom_south_west);
		void llEjectFromLand(string avatar);
        LSLList iwParseString2List(string src, LSLList separators, LSLList spacers, LSLList args);
		LSLList llParseString2List(string src,LSLList separators,LSLList spacers);
		int llOverMyLand(string id);
		string llGetLandOwnerAt(Vector3 pos);
		string llGetNotecardLine(string name,int line);
		Vector3 llGetAgentSize(string id);
		int llSameGroup(string id);
		void llUnSit(string id);
		Vector3 llGroundSlope(Vector3 offset);
		Vector3 llGroundNormal(Vector3 offset);
		Vector3 llGroundContour(Vector3 offset);
		int llGetAttached();
		int llGetFreeMemory();
        int llGetUsedMemory();
        string llGetRegionName();
		float llGetRegionTimeDilation();
		float llGetRegionFPS();
		void llParticleSystem(LSLList rules);
		void llGroundRepel(float height,int water,float tau);
		void llGiveInventoryList(string target,string folder,LSLList inventory);
		void llSetVehicleType(int type);
		void llSetVehicleFloatParam(int param,float value);
		void llSetVehicleVectorParam(int param,Vector3 vec);
        void llSetVehicleRotationParam(int param, Quaternion rot);
		void llSetVehicleFlags(int flags);
		void llRemoveVehicleFlags(int flags);
		void llSitTarget(Vector3 offset,Quaternion rot);
		string llAvatarOnSitTarget();
		void llAddToLandPassList(string avatar,float hours);
		void llSetTouchText(string text);
		void llSetSitText(string text);
		void llSetCameraEyeOffset(Vector3 offset);
		void llSetCameraAtOffset(Vector3 offset);
		string llDumpList2String(LSLList src,string separator);
		int llScriptDanger(Vector3 pos);
		void llDialog(string avatar,string message,LSLList buttons,int chat_channel);
		void llVolumeDetect(int detect);
		void llResetOtherScript(string name);
		int llGetScriptState(string name);
		void llSetRemoteScriptAccessPin(int pin);
		void llRemoteLoadScriptPin(string target,string name,int pin,int running,int start_param);
		void llOpenRemoteDataChannel();
		string llSendRemoteData(string channel,string dest,int idata,string sdata);
		void llRemoteDataReply(string channel,string message_id,string sdata,int idata);
		void llCloseRemoteDataChannel(string channel);
		string llMD5String(string src,int nonce);
		void llSetPrimitiveParams(LSLList rules);
		string llStringToBase64(string str);
		string llBase64ToString(string str);
		string llXorBase64Strings(string s1,string s2);
		float llLog10(float val);
		float llLog(float val);
		LSLList llGetAnimationList(string id);
		void llSetParcelMusicURL(string url);
        string llGetParcelMusicURL();
        Vector3 llGetRootPosition();
		Quaternion llGetRootRotation();
		string llGetObjectDesc();
		void llSetObjectDesc(string name);
		string llGetCreator();
		string llGetTimestamp();
		void llSetLinkAlpha(int linknumber,float alpha,int face);
		int llGetNumberOfPrims();
		string llGetNumberOfNotecardLines(string name);
		LSLList llGetBoundingBox(string obj);
		Vector3 llGetGeometricCenter();
		LSLList llGetPrimitiveParams(LSLList parms);
		string llIntegerToBase64(int number);
		int llBase64ToInteger(string str);
		float llGetGMTclock();
		string llGetSimulatorHostname();
		void llSetLocalRot(Quaternion rot);
		LSLList llParseStringKeepNulls(string src,LSLList separators,LSLList spacers);
		void llRezAtRoot(string inventory,Vector3 pos,Vector3 vel,Quaternion rot,int param);
		int llGetObjectPermMask(int mask);
		void llSetObjectPermMask(int mask,int value);
		int llGetInventoryPermMask(string item,int mask);
		void llSetInventoryPermMask(string item,int mask,int value);
		string llGetInventoryCreator(string item);
		void llOwnerSay(string msg);
		string llRequestSimulatorData(string simulator,int data);
		void llForceMouselook(int mouselook);
		float llGetObjectMass(string id);
		LSLList llListReplaceList(LSLList dest,LSLList src,int start,int end);
		void llLoadURL(string avatar,string message,string url);
		void llParcelMediaCommandList(LSLList command);
		LSLList llParcelMediaQuery(LSLList query);
		int llModPow(int a,int b,int c);
		int llGetInventoryType(string name);
		void llSetPayPrice(int price,LSLList quick_pay_buttons);
		Vector3 llGetCameraPos();
		Quaternion llGetCameraRot();
		void llSetPrimURL(string url);
		void llRefreshPrimURL();
		string llEscapeURL(string url);
		string llUnescapeURL(string url);
		void llMapDestination(string simname,Vector3 pos,Vector3 look_at);
		void llAddToLandBanList(string avatar,float hours);
		void llRemoveFromLandPassList(string avatar);
		void llRemoveFromLandBanList(string avatar);
		void llSetCameraParams(LSLList rules);
		void llClearCameraParams();
		float llListStatistics(int operation,LSLList src);
		int llGetUnixTime();
		int llGetParcelFlags(Vector3 pos);
		int llGetRegionFlags();
		string llXorBase64StringsCorrect(string s1,string s2);
		string llHTTPRequest(string url,LSLList parameters,string body);
		void llResetLandBanList();
		void llResetLandPassList();
		int llGetObjectPrimCount(string object_id);
		LSLList llGetParcelPrimOwners(Vector3 pos);
		int llGetParcelPrimCount(Vector3 pos,int category,int sim_wide);
		int llGetParcelMaxPrims(Vector3 pos,int sim_wide);
		LSLList llGetParcelDetails(Vector3 pos,LSLList parms);
		void llSetLinkPrimitiveParams(int linknumber,LSLList rules);
		void llSetLinkTexture(int linknumber,string texture,int face);
		string llStringTrim(string src,int trim_type);
		void llRegionSay(int channel,string msg);
		LSLList llGetObjectDetails(string id,LSLList parms);

		void llSetClickAction(int action);
		int llGetRegionAgentCount();
		void llTextBox(string avatar,string message,int chat_channel);
		string llGetAgentLanguage(string avatar);
		Vector3 llDetectedTouchUV(int index);
		int llDetectedTouchFace(int index);
		Vector3 llDetectedTouchPos(int index);
		Vector3 llDetectedTouchNormal(int index);
		Vector3 llDetectedTouchBinormal(int index);
		Vector3 llDetectedTouchST(int index);
		string llSHA1String(string src);
		int llGetFreeURLs();
		string llRequestURL();
		string llRequestSecureURL();
		void llReleaseURL(string url);
		void llHTTPResponse(string request_id,int status,string body);
		string llGetHTTPHeader(string request_id,string header);
		int llSetPrimMediaParams(int face,LSLList parms);
        int llSetLinkMedia(int link, int face, LSLList parms);
		LSLList llGetPrimMediaParams(int face,LSLList parms);
        LSLList llGetLinkMedia(int link, int face, LSLList parms);
		int llClearPrimMedia(int face);
        int llClearLinkMedia(int link, int face);
		void llSetLinkPrimitiveParamsFast(int linknumber,LSLList rules);
		LSLList llGetLinkPrimitiveParams(int linknumber,LSLList rules);
		void llLinkParticleSystem(int linknumber,LSLList rules);
		void llSetLinkTextureAnim(int link,int mode,int face,int sizex,int sizey,float start,float length,float rate);
		int llGetLinkNumberOfSides(int link);
		string llGetUsername(string id);
		void llRequestUsername(string id);
		string llGetDisplayName(string id);
		void llRequestDisplayName(string id);
		void iwMakeNotecard(string name,LSLList data);
		void iwAvatarName2Key(string firstName,string lastName);
        void iwLinkTargetOmega(int linknumber, Vector3 axis, float spinrate, float gain);
        int llSetRegionPos(Vector3 position);
        int iwGetLinkInventoryNumber(int linknumber, int type);
        int iwGetLinkInventoryType(int linknumber, string name);
        int iwGetLinkInventoryPermMask(int linknumber, string item, int mask);
        string iwGetLinkInventoryName(int linknumber, int type, int number);
        string iwGetLinkInventoryKey(int linknumber, string name);
        string iwGetLinkInventoryCreator(int linknumber, string item);
        string iwSHA256String(string src);
        void iwTeleportAgent(string agent, string region, Vector3 pos, Vector3 lookat);
        void osTeleportAgent(string agent, string region, Vector3 pos, Vector3 lookat);

        /// <summary>OSSL_Api.cs:1051 - teleport within the current region.</summary>
        void osTeleportAgent(string agent, Vector3 pos, Vector3 lookat);

        /// <summary>OSSL_Api.cs:1015 - teleport to a region named by grid coordinates.</summary>
        void osTeleportAgent(string agent, int regionGridX, int regionGridY, Vector3 pos, Vector3 lookat);
        LSLList osGetAvatarList();
        // OSSL information functions
        string osGetGridName();
        string osGetGridNick();
        string osGetGridHomeURI();
        string osGetGridLoginURI();
        string osGetGridGatekeeperURI();
        string osGetGridCustom(string key);
        Vector3 osGetRegionSize();
        LSLList osGetRegionStats();
        string osGetSimulatorVersion();
        LSLList osGetAgents();
        string osGetMapTexture();
        string osGetPhysicsEngineType();
        string osGetPhysicsEngineName();
        int osGetSimulatorMemory();
        int osGetSimulatorMemoryKB();
        float osGetHealth(string agent);
        string osGetScriptEngineName();
        // OSSL pure helpers
        string osAESEncrypt(string secret, string plainText);
        string osAESDecrypt(string secret, string encryptedText);
        string osAESEncryptTo(string secret, string plainText, string ivString);
        string osAESDecryptFrom(string secret, string encryptedText, string ivString);
        float osAngleBetween(Vector3 a, Vector3 b);

        // ── OSSL sit target, misc and list functions ───────────────────────────────
        /// <summary>OSSL_Api.cs:5985 - this prim's sit target offset.</summary>
        Vector3 osGetSitTargetPos();
        /// <summary>OSSL_Api.cs:5990 - this prim's sit target rotation.</summary>
        Quaternion osGetSitTargetRot();
        /// <summary>OSSL_Api.cs:2721 - Low.</summary>
        string osLoadedCreationDate();
        /// <summary>OSSL_Api.cs:2728 - Low.</summary>
        string osLoadedCreationTime();
        /// <summary>OSSL_Api.cs:2735 - Low.</summary>
        string osLoadedCreationID();
        /// <summary>OSSL_Api.cs:6660 - blackbody temperature to linear sRGB.</summary>
        Vector3 osTemperature2sRGB(float dtemp);
        /// <summary>OSSL_Api.cs:6477 - the pre-2010 llList2ListStrided semantics.</summary>
        LSLList osOldList2ListStrided(LSLList src, int start, int end, int stride);
        /// <summary>OSSL_Api.cs:6695 - the nth occurrence of a sublist within a range.</summary>
        int osListFindListNext(LSLList lsrc, LSLList ltest, int lstart, int lend, int linstance);
        /// <summary>OSSL_Api.cs:6417 - sorts the caller's list itself.</summary>
        void osListSortInPlace(LSLList src, int stride, int ascending);
        /// <summary>OSSL_Api.cs:6422 - the same, keyed on one element of the stride.</summary>
        void osListSortInPlaceStrided(LSLList src, int stride, int strideIndex, int ascending);
        /// <summary>OSSL_Api.cs:6318 - llParticleSystem without the 0.1 s sleep.</summary>
        void osParticleSystem(LSLList rules);
        /// <summary>OSSL_Api.cs:6324 - the same for a link.</summary>
        void osLinkParticleSystem(int linknumber, LSLList rules);
        /// <summary>OSSL_Api.cs:5150 - llPreloadSound for a link, without its sleep.</summary>
        void osPreloadSound(int linknum, string sound);
        /// <summary>OSSL_Api.cs:4704 - mass, centre of mass, inertia, aux.</summary>
        LSLList osGetInertiaData();
        /// <summary>OSSL_Api.cs:3988 - None. Every NPC in the region.</summary>
        LSLList osGetNPCList();
        /// <summary>OSSL_Api.cs:5724 - removes an item from a linked prim.</summary>
        void osRemoveLinkInventory(int linkNumber, string name);
        /// <summary>OSSL_Api.cs:6313 - TerrainUtil's Perlin noise.</summary>
        float osPerlinNoise2D(float x, float y, int octaves, float persistence);
        /// <summary>OSSL_Api.cs:3489 - VeryHigh. Saves another agent's outfit.</summary>
        string osAgentSaveAppearance(string avatarKey, string notecard);
        /// <summary>OSSL_Api.cs:3499 - VeryHigh.</summary>
        string osAgentSaveAppearance(string avatarKey, string notecard, int includeHuds);

        int osApproxEquals(float a, float b);
        int osApproxEquals(float a, float b, float margin);
        /// <summary>OSSL_Api.cs:5432 - the vector form, chosen by type over the float pair.</summary>
        int osApproxEquals(Vector3 va, Vector3 vb);
        /// <summary>OSSL_Api.cs:5469 - the rotation form.</summary>
        int osApproxEquals(Quaternion ra, Quaternion rb);
        /// <summary>OSSL_Api.cs:5450 - the vector form with a margin.</summary>
        int osApproxEquals(Vector3 va, Vector3 vb, float margin);
        /// <summary>OSSL_Api.cs:5491 - the rotation form with a margin.</summary>
        int osApproxEquals(Quaternion ra, Quaternion rb, float margin);
        int osCheckODE();
        string osFormatString(string str, LSLList strings);
        int osIsNotValidNumber(float v);
        int osIsUUID(string thing);
        float osListAsFloat(LSLList src, int index);
        int osListAsInteger(LSLList src, int index);
        string osListAsString(LSLList src, int index);
        Vector3 osListAsVector(LSLList src, int index);
        Quaternion osListAsRotation(LSLList src, int index);
        LSLList osMatchString(string src, string pattern, int start);
        float osMax(float a, float b);
        float osMin(float a, float b);
        int osRegexIsMatch(string input, string pattern);
        float osRound(float value, int ndigits);
        string osSHA256(string input);
        Quaternion osSlerp(Quaternion a, Quaternion b, float amount);
        /// <summary>OSSL_Api.cs:5931 - the vector form, chosen by type over the rotation one.</summary>
        Vector3 osSlerp(Vector3 a, Vector3 b, float amount);
        int osStringStartsWith(string src, string value, int ignorecase);
        int osStringEndsWith(string src, string value, int ignorecase);
        int osStringIndexOf(string src, string value, int ignorecase);
        int osStringIndexOf(string src, string value, int offset, int count, int ignorecase);
        int osStringLastIndexOf(string src, string value, int ignorecase);
        int osStringLastIndexOf(string src, string value, int offset, int count, int ignorecase);
        string osStringRemove(string src, int offset, int count);
        string osStringReplace(string src, string oldvalue, string newvalue);
        string osStringSubString(string src, int offset);
        string osStringSubString(string src, int offset, int length);
        string osUnixTimeToTimestamp(int time);
        float osVecDistSquare(Vector3 a, Vector3 b);
        float osVecMagSquare(Vector3 a);
        // osNpc* on top of BotManager
        int osIsNpc(string npc);
        string osNpcCreate(string firstname, string lastname, Vector3 position, string notecard);
        string osNpcCreate(string firstname, string lastname, Vector3 position, string notecard, int options);
        string osNpcSaveAppearance(string npc, string notecard);
        string osNpcSaveAppearance(string npc, string notecard, int includeHuds);
        void osNpcLoadAppearance(string npc, string notecard);
        string osNpcGetOwner(string npc);
        Vector3 osNpcGetPos(string npc);
        void osNpcMoveTo(string npc, Vector3 pos);
        void osNpcMoveToTarget(string npc, Vector3 target, int options);
        Quaternion osNpcGetRot(string npc);
        void osNpcSetRot(string npc, Quaternion rotation);
        void osNpcStopMoveToTarget(string npc);
        void osNpcSetProfileAbout(string npc, string about);
        void osNpcSetProfileImage(string npc, string image);
        void osNpcSay(string npc, string message);
        void osNpcSay(string npc, int channel, string message);
        void osNpcShout(string npc, int channel, string message);
        void osNpcWhisper(string npc, int channel, string message);
        void osNpcSit(string npc, string target, int options);
        void osNpcStand(string npc);
        void osNpcRemove(string npc);
        void osNpcPlayAnimation(string npc, string animation);
        void osNpcStopAnimation(string npc, string animation);
        void osNpcTouch(string npc, string object_key, int link_num);
        // OSSL side-effect functions (prim, sound, links, attachments, misc)
        void osSetRot(string target, Quaternion rotation);
        void osForceCreateLink(string target, int parent);
        void osForceBreakLink(int linknum);
        void osForceBreakAllLinks();
        int osTeleportObject(string objectUUID, Vector3 targetPos, Quaternion rotation, int flags);
        void osSetSpeed(string ID, float SpeedModifier);
        void osSetOwnerSpeed(float SpeedModifier);
        void osSetContentType(string id, string type);
        void osSetPrimFloatOnWater(int floatYN);
        void osVolumeDetect(int detect);
        void osSetPrimitiveParams(string prim, LSLList rules);
        LSLList osGetPrimitiveParams(string prim, LSLList rules);
        LSLList osGetLinkPrimitiveParams(int linknumber, LSLList rules);
        void osSetProjectionParams(int projection, string texture, float fov, float focus, float amb);
        void osSetProjectionParams(int linknum, int projection, string texture, float fov, float focus, float amb);
        /// <summary>OSSL_Api.cs:3921 - the prim-by-key form, arity 6 like the link form and told apart by type.</summary>
        void osSetProjectionParams(string prim, int projection, string texture, float fov, float focus, float amb);
        void osSetInertia(float mass, Vector3 centerOfMass, Vector3 principalInertiaScaled, Quaternion lslrot);
        void osSetInertiaAsBox(float mass, Vector3 boxSize, Vector3 centerOfMass, Quaternion lslrot);
        void osSetInertiaAsSphere(float mass, float radius, Vector3 centerOfMass);
        void osSetInertiaAsCylinder(float mass, float radius, float length, Vector3 centerOfMass, Quaternion lslrot);
        void osClearInertia();
        void osSetSitActiveRange(float v);
        void osSetLinkSitActiveRange(int linkNumber, float v);
        void osSetStandTarget(Vector3 v);
        void osSetLinkStandTarget(int linkNumber, Vector3 v);
        void osAdjustSoundVolume(int linknum, float volume);
        void osSetSoundRadius(int linknum, float radius);
        void osPlaySound(int linknum, string sound, float volume);
        void osLoopSound(int linknum, string sound, float volume);
        void osLoopSoundMaster(int linknum, string sound, float volume);
        void osLoopSoundSlave(int linknum, string sound, float volume);
        void osPlaySoundSlave(int linknum, string sound, float volume);
        void osTriggerSound(int linknum, string sound, float volume);
        void osTriggerSoundLimited(int linknum, string sound, float volume, Vector3 top_north_east, Vector3 bottom_south_west);
        void osStopSound(int linknum);
        void osTriggerSoundAtPos(string sound, Vector3 position, float gain);
        void osCollisionSound(string impact_sound, float impact_volume);
        void osForceAttachToAvatar(int attachmentPoint);
        void osForceAttachToAvatarFromInventory(string itemName, int attachmentPoint);
        void osForceAttachToOtherAvatarFromInventory(string rawAvatarId, string itemName, int attachmentPoint);
        void osForceDetachFromAvatar();
        void osForceDropAttachment();
        void osForceDropAttachmentAt(Vector3 pos, Quaternion rot);
        void osMessageObject(string objectUUID, string message);
        void osResetAllScripts(int linkset);
        string osRequestURL(LSLList options);
        string osRequestSecureURL(LSLList options);
        string osReplaceString(string src, string pattern, string replace, int count, int start);
        int osClearObjectAnimations();
        void osLocalTeleportAgent(string agent, Vector3 position, Vector3 velocity, Vector3 lookat, int flags);
        int osConsoleCommand(string command);
        // OSSL agent, teleport, kick, animation and group functions
        void osTeleportOwner(string regionName, Vector3 position, Vector3 lookat);
        void osTeleportOwner(int regionGridX, int regionGridY, Vector3 position, Vector3 lookat);
        void osTeleportOwner(Vector3 position, Vector3 lookat);
        void osKickAvatar(string FirstName, string SurName, string alert);
        void osKickAvatar(string agentKey, string alert);
        void osAvatarPlayAnimation(string avatar, string animation);
        void osAvatarStopAnimation(string avatar, string animation);
        string osAvatarName2Key(string firstname, string lastname);
        string osKey2Name(string id);
        string osGetAgentIP(string agent);
        string osOwnerSaveAppearance(string notecard);
        string osOwnerSaveAppearance(string notecard, int includeHuds);
        void osCauseDamage(string avatar, float damage);
        void osCauseHealing(string avatar, float healing);
        void osSetHealth(string avatar, float health);
        void osSetHealRate(string avatar, float healrate);
        void osForceOtherSit(string avatar);
        void osForceOtherSit(string avatar, string target);
        void osDie(string objectUUID);
        void osDropAttachment();
        void osDropAttachmentAt(Vector3 pos, Quaternion rot);
        int osInviteToGroup(string agentId);
        int osEjectFromGroup(string agentId);
        int osAvatarType(string avkey);
        int osAvatarType(string sFirstName, string sLastName);
        // OSSL parcel, estate, terrain, wind and sun functions
        int osSetTerrainHeight(int x, int y, float val);
        int osTerrainSetHeight(int x, int y, float val);
        float osGetTerrainHeight(int x, int y);
        float osTerrainGetHeight(int x, int y);
        void osTerrainFlush();
        int osRegionRestart(float seconds);
        int osRegionRestart(float seconds, string msg);
        void osRegionNotice(string msg);
        void osRegionNotice(string agentID, string msg);
        void osSetRegionWaterHeight(float height);
        void osSetRegionSunSettings(int useEstateSun, int sunFixed, float sunHour);
        void osSetEstateSunSettings(int sunFixed, float sunHour);
        float osGetCurrentSunHour();
        float osGetSunParam(string param);
        float osSunGetParam(string param);
        void osSetSunParam(string param, float value);
        void osSunSetParam(string param, float value);
        string osWindActiveModelPluginName();
        void osSetWindParam(string plugin, string param, float value);
        float osGetWindParam(string plugin, string param);
        void osParcelJoin(Vector3 pos1, Vector3 pos2);
        void osParcelSubdivide(Vector3 pos1, Vector3 pos2);
        void osSetParcelDetails(Vector3 pos, LSLList rules);
        void osParcelSetDetails(Vector3 pos, LSLList rules);
        void osSetParcelMusicURL(string url);
        void osSetParcelMediaURL(string url);
        void osSetParcelSIPAddress(string SIPAddress);
        void osSetTerrainTexture(int level, string texture);
        void osSetTerrainTextures(LSLList textures, int ltypes);
        void osSetTerrainTextureHeight(int corner, float low, float high);
        LSLList osGetParcelDetails(string id, LSLList param);
        // OSSL draw and dynamic-texture functions
        string osSetDynamicTextureURL(string dynamicID, string contentType, string url, string extraParams, int timer);
        string osSetDynamicTextureURLBlend(string dynamicID, string contentType, string url, string extraParams, int timer, int alpha);
        string osSetDynamicTextureURLBlendFace(string dynamicID, string contentType, string url, string extraParams, int blend, int disp, int timer, int alpha, int face);
        string osSetDynamicTextureData(string dynamicID, string contentType, string data, string extraParams, int timer);
        /// <summary>OSSL_Api.cs:790 - the face form, arity 6 like DataBlend and told apart by nothing but its name.</summary>
        string osSetDynamicTextureDataFace(string dynamicID, string contentType, string data, string extraParams, int timer, int face);
        string osSetDynamicTextureDataBlend(string dynamicID, string contentType, string data, string extraParams, int timer, int alpha);
        string osSetDynamicTextureDataBlendFace(string dynamicID, string contentType, string data, string extraParams, int blend, int disp, int timer, int alpha, int face);
        string osDrawResetTransform(string drawList);
        string osDrawRotationTransform(string drawList, float x);
        string osDrawScaleTransform(string drawList, float x, float y);
        string osDrawTranslationTransform(string drawList, float x, float y);
        string osMovePen(string drawList, int x, int y);
        string osDrawLine(string drawList, int startX, int startY, int endX, int endY);
        string osDrawLine(string drawList, int endX, int endY);
        string osDrawText(string drawList, string text);
        string osDrawEllipse(string drawList, int width, int height);
        string osDrawFilledEllipse(string drawList, int width, int height);
        string osDrawRectangle(string drawList, int width, int height);
        string osDrawFilledRectangle(string drawList, int width, int height);
        string osDrawFilledPolygon(string drawList, LSLList x, LSLList y);
        string osDrawPolygon(string drawList, LSLList x, LSLList y);
        string osSetFontSize(string drawList, int fontSize);
        string osSetFontName(string drawList, string fontName);
        string osSetPenSize(string drawList, int penSize);
        string osSetPenColor(string drawList, string color);
        /// <summary>OSSL_Api.cs:1400 - the vector form, arity 2 like the colour-name one.</summary>
        string osSetPenColor(string drawList, Vector3 color);
        string osSetPenColor(string drawList, Vector3 color, float alpha);
        string osSetPenColour(string drawList, string colour);
        string osSetPenCap(string drawList, string direction, string type);
        string osDrawImage(string drawList, int width, int height, string imageUrl);
        Vector3 osGetDrawStringSize(string contentType, string text, string fontName, int fontSize);
        // OSSL read-only remainder
        string osGetNotecardLine(string name, int line);
        string osGetNotecard(string name);
        int osGetNumberOfNotecardLines(string name);
        string osGetAvatarHomeURI(string uuid);
        LSLList osGetNumberOfAttachments(string avatar, LSLList attachmentPoints);
        string osGetRegionMapTexture(string regionNameOrID);
        int osGetLinkNumber(string name);
        string osGetRezzingObject();
        int osListenRegex(int channelID, string name, string ID, string msg, int regexBitfield);
        string osDetectedCountry(int number);
        string osGetAgentCountry(string id);
        string osGetGender(string rawAvatarId);
        float osGetHealRate(string avatar);
        float osGetApparentTime();
        string osGetApparentTimeString(int format24);
        float osGetApparentRegionTime();
        string osGetApparentRegionTimeString(int format24);
        float osGetPSTWallclock();
        string osGetLastChangedEventKey();
        Vector3 osGetLinkColor(int link, int face);
        float osGetSitActiveRange();
        float osGetLinkSitActiveRange(int linkNumber);
        Vector3 osGetStandTarget();
        Vector3 osGetLinkStandTarget(int linkNumber);
        int osGetPrimCount();
        int osGetPrimCount(string object_id);
        int osGetSittingAvatarsCount();
        int osGetSittingAvatarsCount(string object_id);
        int osGetParcelDwell(Vector3 pos);
        string osGetParcelID();
        LSLList osGetParcelIDs();
        string osGetInventoryLastOwner(string itemNameorid);
        string osGetInventoryItemKey(string name);
        string osGetInventoryName(string itemId);
        string osGetInventoryDesc(string itemNameorid);
        LSLList osGetInventoryItemKeys(int type);
        LSLList osGetInventoryNames(int type);
        string osGetLinkInventoryName(int linkNumber, string itemId);
        string osGetLinkInventoryDesc(int linkNumber, string itemNameorid);
        string osGetLinkInventoryKey(int linkNumber, string name, int type);
        LSLList osGetLinkInventoryKeys(int linkNumber, int type);
        string osGetLinkInventoryItemKey(int linkNumber, string name);
        LSLList osGetLinkInventoryItemKeys(int linkNumber, int type);
        LSLList osGetLinkInventoryNames(int linkNumber, int type);
        string llAvatarOnLinkSitTarget(int linknumber);
        string iwGetLastOwner();
        void iwRemoveLinkInventory(int linknumber, string item);
        void iwGiveLinkInventory(int linknumber, string destination, string inventory);
        void iwGiveLinkInventoryList(int linknumber, string target, string folder, LSLList inventory);
        string iwGetNotecardSegment(string name, int line, int startOffset, int maxLength);
        string iwGetLinkNumberOfNotecardLines(int linknumber, string name);
        string iwGetLinkNotecardLine(int linknumber, string name, int line);
        string iwGetLinkNotecardSegment(int linknumber, string name, int line, int startOffset, int maxLength);
        int iwActiveGroup(string agent, string group);
        string iwAvatarOnLink(int linknumber);
        void llRegionSayTo(string destId, int channel, string msg);
        string iwGetLinkInventoryDesc(int linknumber, string name);
        string llGenerateKey();
        string iwGetLinkInventoryLastOwner(int linknumber, string name);
        string llGetEnv(string name);
        void llSetAngularVelocity(Vector3 force, int local);
        LSLList llGetPhysicsMaterial();
        void llSetPhysicsMaterial(int mask, float gravityMultiplier, float restitution, float friction, float density);
        void llSetVelocity(Vector3 force, int local);
        void iwRezObject(string inventory, Vector3 pos, Vector3 vel, Quaternion rot, int param);
        void iwRezAtRoot(string inventory, Vector3 pos, Vector3 vel, Quaternion rot, int param);
        string iwRezAt(string inventory, int rezAtRoot, Vector3 pos, Vector3 vel, Quaternion rot, int param);
        string iwRezPrim(LSLList primParams, LSLList particleSystem, LSLList inventory, Vector3 pos, Vector3 vel, Quaternion rot, int param);
        LSLList llGetAgentList(int scope, LSLList options);
        LSLList iwGetAgentList(int scope, Vector3 minPos, Vector3 maxPos, LSLList paramList);
        LSLList iwGetWorldBoundingBox(string obj);
        int llSetMemoryLimit(int limit);
        int llGetMemoryLimit();
        void llManageEstateAccess(int action, string avatar);
        int iwSubStringIndex(string source, string pattern, int offset, int isCaseSensitive);
        void llLinkSitTarget(int link, Vector3 offset, Quaternion rot);
		float llGetMassMKS();
        float iwGetObjectMassMKS(string id);
        void llSetLinkCamera(int link, Vector3 eyeOffset, Vector3 cameraAt);
        void iwSetGround(int x1, int y1, int x2, int y2, float height);
        void llSetContentType(string request_id, int content_type);
        string llJsonGetValue(string json, LSLList specifiers);
        string llJsonValueType(string json, LSLList specifiers);
        string llJsonSetValue(string json, LSLList specifiers, string value);
        string llList2Json(string type, LSLList values);
        LSLList llJson2List(string src);
        void iwSetWind(int type, Vector3 offset, Vector3 speed);
        Vector3 iwWind(Vector3 offset);
        int iwHasParcelPowers(int groupPower);
        Vector3 iwGroundSurfaceNormal(Vector3 offset);
        string iwRequestAnimationData(string name);
        LSLList llCastRay(Vector3 start, Vector3 end, LSLList options);
        void llSetKeyframedMotion(LSLList keyframes, LSLList options);
        int iwGetLocalTime();
        int iwGetLocalTimeOffset();
        string iwFormatTime(int unixtime, int isUTC, string format);
        int iwCheckRezError(Vector3 pos, int isTemp, int landImpact);

        void botCreateBot(string FirstName, string LastName, string outfitName, Vector3 startPos, int options);//Returns string via async return
        void botAddTag(string botID, string tag);
        void botRemoveTag(string botID, string tag);
        LSLList botGetBotsWithTag(string tag);
        void botRemoveBotsWithTag(string tag);
        void botRemoveBot(string botID);
        void botPauseMovement(string botID);
        void botResumeMovement(string botID); 
        void botWhisper(string botID, int channel, string message);
        void botSay(string botID, int channel, string message);
        void botShout(string botID, int channel, string message);
        void botStartTyping(string botID);
        void botStopTyping(string botID);
        void botSendInstantMessage(string botID, string userID, string message);
        void botSitObject(string botID, string objectID);
        void botStandUp(string botID);
        string botGetOwner(string botID);
        int botIsBot(string userID);
        void botTouchObject(string bot, string objectID);
        void botSetMovementSpeed(string botID, float speed);
        Vector3 botGetPos(string botID);
        string botGetName(string botID);
        void botStartAnimation(string botID, string animation);
        void botStopAnimation(string botID, string animation);
        void botTeleportTo(string botID, Vector3 position);
        void botChangeOwner(string botID, string newOwnerID);
        LSLList botGetAllBotsInRegion();
        LSLList botGetAllMyBotsInRegion();
        int botFollowAvatar(string botID, string avatar, LSLList options);
        void botStopMovement(string botID);
        void botSetNavigationPoints(string botID, LSLList positions, LSLList movementTypes, LSLList options);
        void botRegisterForNavigationEvents(string botID);
        void botSetProfile(string botID, string aboutText, string email, string firstLifeAboutText,
            string firstLifeImageUUID, string imageUUID, string profileURL);
        void botSetRotation(string botID, Quaternion rotation);
        void botGiveInventory(string botID, string destination, string inventory);
        void botSensor(string botID, string name, string id, int type, float range, float arc);
        void botSensorRepeat(string botID, string name, string id, int type, float range, float arc, float rate);
        void botSensorRemove();
        string iwDetectedBot();
        int botListen(string botID, int channel, string name, string id, string msg);
        void botRegisterForCollisionEvents(string botID);
        void botDeregisterFromCollisionEvents(string botID);
        void botDeregisterFromNavigationEvents(string botID);
        void botSetOutfit(string outfitName);
        void botRemoveOutfit(string outfitName);
        void botChangeOutfit(string botID, string outfitName);
        void botGetBotOutfits();//Returns LSLList via async return
        void botWanderWithin(string botID, Vector3 origin, float xDistance, float yDistance, LSLList options);
        void botMessageLinked(string botID, int num, string msg, string id);
        void botSetProfileParams(string botID, LSLList profileInformation);
        LSLList botGetProfileParams(string botID, LSLList profileInformation);
        int iwGetAppearanceParam(string who, int which);
        int iwChar2Int(string src, int index);
        string iwInt2Char(int num);
        string iwReplaceString(string str, string pattern, string replacement);
        string iwFormatString(string str, LSLList values);
        int iwMatchString(string str, string pattern, int matchType);
        string iwStringCodec(string str, string pattern, int operation, LSLList extraParams);
        int iwMatchList(LSLList list1, LSLList list2, int matchType);
        Vector3 iwColorConvert(Vector3 input, int color1, int color2);
        Vector3 iwNameToColor(string name);
        int iwVerifyType(string str, int type);
        int iwGroupInvite(string group, string user, string role);
        int iwGroupEject(string group, string user);
        string iwGetAgentData(string id, int data);
        int iwIsPlusUser(string id);
        void llAttachToAvatarTemp(int attachPoint);
        int iwListIncludesElements(LSLList src, LSLList elements, int any);
        string iwReverseString(string src);
        LSLList iwReverseList(LSLList src, int stride);
        LSLList iwSearchInventory(int type, string pattern, int matchtype);
        LSLList iwSearchLinkInventory(int link, int type, string pattern, int matchtype);
        int iwIntRand(int max);
        int iwIntRandRange(int min, int max);
        float iwFrandRange(float min, float max);
        void botSearchBotOutfits(string pattern, int matchType, int start, int end);//Returns LSLList via async return
        LSLList iwListRemoveElements(LSLList src, LSLList elements, int count, int mode);
        LSLList iwListRemoveDuplicates(LSLList src);
        void iwStartLinkAnimation(int link, string anim);
        void iwStopLinkAnimation(int link, string anim);
        int iwClampInt(int value, int min, int max);
        float iwClampFloat(float value, float min, float max);
        LSLList iwSearchLinksByName(string pattern, int matchType, int linksOnly);
        LSLList iwSearchLinksByDesc(string pattern, int matchType, int linksOnly);
        int botHasTag(string botID, string tag);
        LSLList botGetBotTags(string botID);
        int iwValidateURL(string url);
        int iwRemoteLoadScriptPin(string target,string name,int pin,int running,int start_param);
        void iwDeliverInventory(int linknumber, string destination, string inventory);
        void iwDeliverInventoryList(int linknumber, string target, string folder, LSLList inventory);
        LSLList llGetAttachedList(string avatar);
        int llReturnObjectsByOwner(string owner, int scope);
        int llReturnObjectsByID(LSLList objects);
        string llTransferLindenDollars(string destination, int amount );
        string iwGiveMoney(string destination, int amount);
        void iwStandTarget(Vector3 offset, Quaternion rot);
        void iwLinkStandTarget(int link, Vector3 offset, Quaternion rot);
        string llGetAnimationOverride(string anim_state);
        void llSetAnimationOverride(string anim_state, string anim);
        void llResetAnimationOverride(string anim_state);
		// === ADD THESE LINES to ISystemAPI.cs ===
		// Insert BEFORE the closing "}" of the interface, after "void llResetAnimationOverride(string anim_state);"

        // ── SL compatibility functions ──
        string llChar(int unicode);
        int llOrd(string src, int index);
        string llComputeHash(string src, string algorithm);
        string llDetectedRezzer(int number);
        string llGetInventoryDesc(string item);
        string llGetInventoryAcquireTime(string item);
        string llName2Key(string name);
        float llGetRegionTimeOfDay();
        float llGetSimStats(int statType);
        int llGetSPMaxMemory();
        LSLList llGetObjectAnimationNames();
        string llGetObjectLinkKey(string objectId, int linknumber);
        void llDerezObject(string id);

        // ── Medium-effort SL compatibility ──
        void llTeleportAgent(string agent, string landmark, Vector3 pos, Vector3 lookAt);
        void llTeleportAgentGlobalCoords(string agent, Vector3 globalCoords, Vector3 regionPos, Vector3 lookAt);
        int llScaleByFactor(float factor);
        float llGetMaxScaleFactor();
        float llGetMinScaleFactor();
        float llGetCameraAspect();
        float llGetCameraFOV();
        LSLList llGetAttachedListFiltered(string avatar, int attachmentPoint);
        int llIsFriend(string agent);
        LSLList llGetVisualParams(string agent, LSLList paramIndices);
        string llGetNotecardLineSync(string name, int line);
        int llFindNotecardTextSync(string name, string text, int line, int caseSensitive);
        void llStartObjectAnimation(string anim);
        void llStopObjectAnimation(string anim);
        int llGetLinkSitFlags(int link);
        void llSetLinkSitFlags(int link, int flags);

        // ── String/List/Crypto SL compatibility ──
        string llReplaceSubString(string src, string pattern, string replacement, int count);
        int llListFindStrided(LSLList src, LSLList test, int start, int end, int stride);
        LSLList llList2ListSlice(LSLList src, int start, int end, int stride, int slice_index);
        LSLList llSortListStrided(LSLList src, int stride, int stride_index, int ascending);
        int llListFindListNext(LSLList src, LSLList test, int ofs);
        string llHMAC(string msg, string privateKey, string algorithm);
        string llSHA256String(string src, int nonce);
        void llLinkPlaySound(int link, string sound, float volume, int flags);

        /// <summary>LSL_Api.cs:2939 - the three-argument form, flags defaulted to 0.</summary>
        void llLinkPlaySound(int link, string sound, float volume);
        Vector3 llLinear2sRGB(Vector3 color);
        Vector3 llSRGB2Linear(Vector3 color);
		Vector3 llWorldPosToHUD(Vector3 worldPos);

        // ── Linkset Data ──
        int llLinksetDataAvailable();
        int llLinksetDataCountKeys();
        string llLinksetDataRead(string name);
        string llLinksetDataReadProtected(string name, string pass);
        int llLinksetDataWrite(string name, string value);
        int llLinksetDataWriteProtected(string name, string value, string pass);
        int llLinksetDataDelete(string name);
        int llLinksetDataDeleteProtected(string name, string pass);
        void llLinksetDataReset();
        LSLList llLinksetDataDeleteFound(string pattern, string pass);
        int llLinksetDataCountFound(string pattern);
        LSLList llLinksetDataListKeys(int start, int count);
        LSLList llLinksetDataFindKeys(string pattern, int start, int count);

        // ── Tier 1: EEP / Environment ──
        int llGetDayLength();
        int llGetDayOffset();
        int llGetRegionDayLength();
        int llGetRegionDayOffset();
        Vector3 llGetMoonDirection();
        Quaternion llGetMoonRotation();
        Quaternion llGetSunRotation();
        Vector3 llGetRegionSunDirection();
        Quaternion llGetRegionSunRotation();
        Vector3 llGetRegionMoonDirection();
        Quaternion llGetRegionMoonRotation();
		Vector3 llGetRegionLightDir();

        // ── Tier 2: PBR / GLTF Materials ──
        string llGetRenderMaterial(int face);
        void llSetRenderMaterial(string materialId, int face);
        int llIsLinkGLTFMaterial(int link, int face);
        int llSetLinkGLTFOverrides(int link, int face, LSLList overrides);
        void llRenderMaterial(string materialId);

        // ── Tier 3: Combat 2.0 ──
        float llGetHealth(string id);
        void llAdjustDamage(int number, float newDamage);
        void llSetHealth(string id, float health);

		// ── Tier 4: Pathfinding Shims ──
        LSLList llGetClosestNavPoint(Vector3 point, LSLList options);
        LSLList llGetStaticPath(Vector3 start, Vector3 end, float radius, LSLList parameters);
        void llExecCharacterCmd(int command, LSLList parameters);
        void llDeleteCharacter();
		// -- Pathfinding Character Functions --
		void llCreateCharacter(LSLList options);
		void llNavigateTo(Vector3 pos, LSLList options);
		void llUpdateCharacter(LSLList options);
		void llPursue(string targetID, LSLList options);
		void llEvade(string targetID, LSLList options);
		void llFleeFrom(Vector3 source, float distance, LSLList options);
		void llWanderWithin(Vector3 origin, Vector3 distances, LSLList options);
		void llPatrolPoints(LSLList points, LSLList options);
		
		// ── Tier 5: Experience KVP Store ──
        string llCreateKeyValue(string key, string value);
        string llReadKeyValue(string key);
        string llUpdateKeyValue(string key, string value, string check);
        string llDeleteKeyValue(string key);
        string llKeyCountKeyValue();
        string llKeysKeyValue(int start, int count);
        string llDataSizeKeyValue();
        int llClearKeyValue();
        string llCreateKeyValueSL(string key, string value);
        string llReadKeyValueSL(string key);
        string llUpdateKeyValueSL(string key, string value, string check);
		
        // ── Tier 6: Standalone ──
        string llSignRSA(string data, string privateKeyPem, string algorithm);
        int llVerifyRSA(string data, string signature, string publicKeyPem, string algorithm);

        // ── Tier 7: EEP Environment ──
        LSLList llGetEnvironment(Vector3 pos, LSLList paramList);
        int llSetEnvironment(Vector3 pos, LSLList paramList);
        int llReplaceEnvironment(Vector3 pos, string environment, int track, int day_length, int day_offset);

        // ── Tier 7b: Agent Environment + User Key ──
        string llRequestUserKey(string username);
        int llSetAgentEnvironment(string agentID, float transition, LSLList paramList);
        int llReplaceAgentEnvironment(string agentID, float transition, string environment);

        // ── Tier 8: Remaining SL Gaps ──
        string llGetExperienceErrorMessage(int error);
        void llSetAgentRot(Quaternion rot, int relative);
        void llOpenFloater(string name, string url, LSLList paramList);
        void llCloseFloater(string name);
        int llSitOnLink(string agentID, int link);
        string llRezObjectWithParams(string inventory, LSLList paramList);
        string llGetMaterialOverride(int face, LSLList paramList);

        // ── Phase 31: 19 new functions (TableIndex 643–661) ──
        int llHash(string src);
        void llLinkAdjustSoundVolume(int link, float volume);
        void llLinkSetSoundQueueing(int link, int queue);
        void llLinkSetSoundRadius(int link, float radius);
        void llLinkStopSound(int link);
        void llScriptProfiler(int flags);
        void llGiveAgentInventory(string destination, string inventory);
        void llMapBeacon(string agent, string text, Vector3 color);
        string llGetStartString();
        void llSetGroundTexture(string texture, int corner);
        void llTargetedEmail(int targetType, string address, string subject, string message);

        // ---- SL names and arities. Older spellings above stay as aliases. ----
        Vector3 llsRGB2Linear(Vector3 srgb);
        LSLList llListSortStrided(LSLList src, int stride, int stride_index, int ascending);
        string llSHA256String(string src);
        void llTargetedEmail(int target, string subject, string message);
        string llUpdateKeyValue(string k, string v, int isChecked, string original_value);
        int llDerezObject(string id, int flag);
        int llTransferOwnership(string destination);
        LSLList llDetectedDamage(int number);
        void llDamage(string target, float amount, int damageType);
        void llSetLinkRenderMaterial(int link, string materialId, int face);
        string llXorBase64(string s1, string s2);
        void llRequestExperiencePermissions(string agent, string name);
        int llAgentInExperience(string agent);
        LSLList llGetExperienceDetails(string experienceId);

        // ── Phase 33: 5 new functions (TableIndex 662–666) ──
        LSLList llGetPayPrice();
        Quaternion llGetAgentRot();
        string llGetGroundTexture(int corner);
        int llGetVehicleFlags();
        LSLList llGetLinkGLTFOverrides(int link, int face);

        // ── Phase 34: Bot Persistence (TableIndex 667–671) ──
        int botSetPersistent(string botID, int ttlSeconds);
        int botRemovePersistent(string botID);
        int botIsPersistent(string botID);
        string botGetPersistentData(string botID, string key);
        int botSetPersistentData(string botID, string key, string value);
    }
}